### ISSUE TITLE
折线图上hover时部分css属性没有生效

### ISSUE THREAD

**Issue by 962464zyy** [ecomfe/zrender#1003]
display: -webkit-box;
-webkit-box-orient: vertical;
-webkit-line-clamp: 2;
这些属性在折线图上hover时似乎并没有生效，请问有人遇到过吗？怎么解决的呢？
![image](https://user-images.githubusercontent.com/58205923/229468486-1e7df82d-f37a-4f64-8dae-1dd0f7b5e390.png)

**Comment by plainheart** [comment]
如果可以，还请给一个示例链接，便于我们实地检查调试。

**Comment by 962464zyy** [comment]
你好，这里还原了一下，还请看一下
https://codesandbox.io/p/sandbox/relaxed-shtern-6qyzc0?file=%2Fsrc%2Fcomponents%2FChartTooltip%2Findex.module.less&selection=%5B%7B%22endColumn%22%3A4%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A4%2C%22startLineNumber%22%3A19%7D%5D

**Comment by 962464zyy** [comment]
> 你好，这里还原了一下，还请看一下 https://codesandbox.io/p/sandbox/relaxed-shtern-6qyzc0?file=%2Fsrc%2Fcomponents%2FChartTooltip%2Findex.module.less&selection=%5B%7B%22endColumn%22%3A4%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A4%2C%22startLineNumber%22%3A19%7D%5D

**Comment by plainheart** [comment]
@962464zyy 怎么把 issue 关了？是解决了吗？

**Comment by 962464zyy** [comment]
哦 关错了 问题还在

**Comment by plainheart** [comment]
看了下，是 tooltip 的容器样式设置了 `white-space: nowrap`，子元素继承了该样式导致其不会换行，可以手动给子元素加上 `    white-space: normal` 覆盖一下。

**Comment by 962464zyy** [comment]
是的  谢谢您
