### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by ufxelv80** [ecomfe/zrender#1045]
我导入的时候使用   import * as zrender from 'zrender/src/zrender';   导入但是控制台为何报错 Uncaught Error: Renderer 'undefined' is not imported. Please import it first.

**Comment by plainheart** [comment]
需要手动导入并注册下渲染器，下为注册 CanvasRenderer 的示例。

```js
import * as zrender from 'zrender'
import CanvasPainter from 'zrender/lib/canvas/Painter'

zrender.registerPainter('canvas', CanvasPainter)
```

**Comment by ufxelv80** [comment]
@plainheart 好的，谢谢！！！
