### ISSUE TITLE
VUE3 + Vite build ERROR: Cs[o] is not a constructor 

### ISSUE THREAD

**Issue by lordrepha1980** [ecomfe/zrender#1069]
In the finished build with Vite and Vue3 I get the error 

Cs[o] is not a constructor

The build itself runs through only when calling up the charts in the finished website this error occurs and all charts are not displayed

**Comment by plainheart** [comment]
Did you import and use the required `CanvasPainter` or `SVGPainter`? Like this,

```js
import * as zrender from 'zrender' ;
import CanvasPainter from 'zrender/lib/canvas/Painter';
// import SVGPainter from 'zrender/lib/svg/Painter';
zrender.registerPainter('canvas', CanvasPainter);
```
