### ISSUE TITLE
The global variable pathProxyForDraw references _ctx, causing the CanvasRenderingContext2D object to fail to be deallocated, causing a memory leak

### ISSUE THREAD

**Issue by wenbei421** [ecomfe/zrender#1082]
![image](https://github.com/ecomfe/zrender/assets/6428597/4135ce97-ea6f-4583-8acf-8f9dabd93c48)
![image](https://github.com/ecomfe/zrender/assets/6428597/40e0808a-8692-4564-aa15-0e9dcdb986d7)

**Comment by plainheart** [comment]
@pissang Could you have a look?

**Comment by plainheart** [comment]
@wenbei421 可以麻烦提供一个复现例子吗？怀疑是你那边在 zrender dispose 之后，未将声明的元素也置为 null 以释放内存。

**Comment by plainheart** [comment]
未收到您的回应，先关闭 issue 了哈，有问题可以继续评论。

**Comment by wenbei421** [comment]
是使用echarts发现的

**Comment by plainheart** [comment]
创建个 demo 复现一下？
