### ISSUE TITLE
zrender在npm官网版本是2.0.2，不是2.0.7？

### ISSUE THREAD

**Issue by magicxie** [ecomfe/zrender#120]
这个是npm的问题吗，摸不着头脑

https://www.npmjs.com/package/zrender
![image](https://cloud.githubusercontent.com/assets/920690/6287710/8dcd616e-b94e-11e4-8fe8-8450c0da1a80.png)

**Comment by blackbing** [comment]
+1 為什麼版本更新了不推 npm?

**Comment by ieiayaobb** [comment]
+1 echarts依赖最新的zrender，这边不推的话echarts也没法使用了

**Comment by dtlovebmm1314** [comment]
2.0.2  我刚刚才npm得

**Comment by luqin** [comment]
zrender在npm被占用
请使用：https://www.npmjs.com/package/zrenderjs 或者 https://www.npmjs.com/package/zrender.js
建议配合webpack使用

**Comment by magicxie** [comment]
现在3.0的zrender.js的git库指向@luqin 的fork，package.json里是2.1.1。
项目主页没有roadmap的公告，如果是历史遗留问题，还望能借3.0升级一次性梳理清楚，该废库的就废了吧。靠issue来说明版本和使用方式对开发和用户都不是长久之计。

**Comment by luqin** [comment]
@magicxie 这是我的 fork 版本，因为我需要 webpack 集成 echarts，所以不得已发布了 npm 版本。

**Comment by luqin** [comment]
官方好像对于处理 issue 不太积极，导致 issue 积累过多。
