### ISSUE TITLE
大神，再请教下。调试了各种参数，怎么把鼠标HOVER图形发光这个给取消掉？

### ISSUE THREAD

**Issue by zacard-orc** [ecomfe/zrender#121]
zr.addShape(new XShape({
                        style : {
                            x : 20,
                            y : 20,
                            r : 30,
                            hoverable:false,
                            lineJoin : 'round',
                            highlightStyle:false,
                            color : 'rgba(0,0,0,1)',          // rgba supported
                            lineWidth : 0,
                            strokeColor:'#000000',
                            shadowColor:'#000000'
                        }
                    }));

期望圆就是黑色的圆，但HOVER上去后，外面多一层黄色的光。试了几个参数貌似都没效果？

**Comment by pissang** [comment]
设置 highlightStyle 的 lineWidth 为 0

**Comment by zacard-orc** [comment]
非常感谢
