### ISSUE TITLE
鼠标单击拖动随便画线如何实现呢(已解决，求讨论)

### ISSUE THREAD

**Issue by zuoliang0** [ecomfe/zrender#129]
实现画板功能怎么实现画线和橡皮擦功能？

**Comment by 178620086** [comment]
$('canvas').unbind();//去除以前绑定的事件
                var s; //定义路径对象
                var sL = []; //路径数组
                var isDraw = false;
                $('canvas').mousedown(function(e) {
                    isDraw = true; //表示正在画线了
                    s = new PolylineShape({ //初始化线条
                        style: {
                            pointList: sL,
                            smooth: 'spline',
                            brushType: 'stroke',
                            color: 'rgba(220, 20, 60, 0.8)',
                            strokeColor: "rgba(220, 20, 60, 0.8)",
                            lineWidth: 2
                                // lineType : 'dotted'
                        }
                    });
                    zr.addShape(s); //将线条添加到图层上
                });
                $('canvas').mousemove(function(e) {
                    if (isDraw) { //判断是否是画线状态
                        var x = e.pageX - this.offsetLeft;
                        var y = e.pageY - this.offsetTop; //获取鼠标位置
                        sL.push([x, y]); //将位置存入数组
                        zr.modShape(s.id, {
                            pointList: sL
                        }); //更新线条对象的位置数组
                        zr.refresh(); //刷新图层
                    }
                });
                $('canvas').mouseup(function(e) {
                    isDraw = false; //退出画线状态
                    sL = []; //清空线条路经,若不清空将会和上次画线连接到一起
                    // s=null;    //清空线条对象
                });

**Comment by 178620086** [comment]
现在正在想怎么实现橡皮檫功能，实在不行用点选删除算了

**Comment by wangwufan** [comment]
好厉害

**Comment by lzpong** [comment]
lz 你做这个,还不如不要用这个东西, 更方便你实现你要的共更能,  网上有 直接用 canvas 事件黑板(黑板擦)的
