### ISSUE TITLE
build/zrender.js package，通过requirejs加载，无法使用其中的zrender/shape/Circle

### ISSUE THREAD

**Issue by MichaelHu** [ecomfe/zrender#133]
build/zrender.js是r.js生成的，在build.js配置中已经包含'zrender/shape/Circle'，所以在使用的时候，如下代码：    

    require(['zrender'], function(zrender){
        var zr = zrender.init(document.getElementById('main'));
        var CircleShape = require('zrender/shape/Circle'); 
        /* 这一步出现Uncaught Error: Module name "zrender/shape/Circle" has not been loaded 
            yet for context: _
        */
        ...
    });

但是在zrender.js这个package中，已经打包了zrender/shape/Circle这个模块了：

    define(
        'zrender/shape/Circle',['require','./Base','../tool/util'],function (require) {
        ....

请问具体该如何使用？

**Comment by ligai322** [comment]
你可以写成这样试一下
require(['zrender','zrender/shape/Circle'], function(zrender,CircleShape ){
    var zr = zrender.init(document.getElementById('main'));
    /* 这一步出现Uncaught Error: Module name "zrender/shape/Circle" has not been loaded 
        yet for context: _
    */
    ...
});
