### ISSUE TITLE
Shape Image路径不支持data:png

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/zrender#142]
我是从echart游到这里来的。原因是这样，echart的toolbox可以自定义图标。格式是"image://path/to/your/image.png"。这个路径必须是绝对路径，但我在实现的是一个库，我并不知道用户会把这个库定义在什么位置。想请教如何解决这种问题。

此外，我想了一下，是不是可以考虑支持`data:image/png,base64...`的方式来定义图片呢？这几年使用图片文件的方式似乎不太流行，用css内联的方式去定义比较的简单。希望zrender能支持，能尽快支持。

**Comment by pissang** [comment]
支持 base64 格式作为图片的，路径的话是相对于页面的路径

**Comment by stanleyxu2005** [comment]
@pissang 我是参考这个例子http://echarts.baidu.com/doc/example/toolbox.html处理的

我把
```
myTool : {
                show : true,
                title : '自定义扩展方法',
                icon : 'image://../asset/ico/favicon.png',
                onclick : function (){
                    alert('myToolHandler')
                }
            }
```
里面icon的地址换成了`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAICAYAAAArzdW1AAAAFUlEQVR4nGP8//8/AyHARFDFsFcEAHkjAw3jrppVAAAAAElFTkSuQmCC`

这样是没有图片出来的。Chrome里面看，这个request一直处于pending的状态。
