### ISSUE TITLE
npm麻烦发布一下最新版本

### ISSUE THREAD

**Issue by cnchanning** [ecomfe/zrender#146]
npm麻烦发布一下最新版本，echarts依赖2.11

**Comment by abo** [comment]
+1

**Comment by stanleyxu2005** [comment]
自己build不是更好，用echarts-optimizer。顺便还可以丢弃那些不需要的模块，以减小整体尺寸呢。

**Comment by luqin** [comment]
zrender在npm被占用
请使用：https://www.npmjs.com/package/zrenderjs 或者 https://www.npmjs.com/package/zrender.js
