### ISSUE TITLE
弱弱的问一下   亲爱滴zrender不支持webpack 下的npm使用么。。。。

### ISSUE THREAD

**Issue by dtlovebmm1314** [ecomfe/zrender#159]

**Comment by luqin** [comment]
@dtlovebmm1314 
zrender在npm被占用，请使用：https://www.npmjs.com/package/zrenderjs或者https://www.npmjs.com/package/zrender.js

**Comment by dtlovebmm1314** [comment]
@luqin   thanks

**Comment by pissang** [comment]
https://www.npmjs.com/package/zrender 以支持 npm 获取 zrender
