### ISSUE TITLE
完全不会用

### ISSUE THREAD

**Issue by df257** [ecomfe/zrender#179]
官方页面没有完整的新手教程，对于我们这种新手，简直云里雾里。首先，我们不知道引入require.js，然后是引入require.js后，还是没效果！真是虐菜啊。。。。

**Comment by df257** [comment]
连个门都看不见。。。

**Comment by iamweilee** [comment]
其实很简单，耐心性子做一下试试

**Comment by Marshal-T** [comment]
同觉得刚入门有点懵逼，软件下齐了，却不会用。有大神知道网易云课堂里《echarts基础教程》能不能解决零基础的问题，真的是零基础！！

**Comment by maqunboy** [comment]
这个下载了怎么用不知道 ，有相应的说明文档么？
