### ISSUE TITLE
doc生成文档报错

### ISSUE THREAD

**Issue by Jerry-goodboy** [ecomfe/zrender#183]
最新的代码，环境为MAC OS X 10.11.5 ，执行步骤为
$ npm install
$ grunt demo
在执行 grunt demo 时报错，dist文件夹下面为空，截图如下，
<img width="730" alt="2016-05-25 11 55 17" src="https://cloud.githubusercontent.com/assets/9030784/15527746/b0fc9b2e-226f-11e6-8a23-8e99be73e5e2.png">
加上 --force 也报错
<img width="725" alt="2016-05-25 11 55 41" src="https://cloud.githubusercontent.com/assets/9030784/15527766/cd18adc0-226f-11e6-8a4e-cd2316a40246.png">

**Comment by Jerry-goodboy** [comment]
@beebole @leeight @cnberg @firede @chriswong 大神，求指导

**Comment by firede** [comment]
要生成文档？在项目目录：
```
npm i -g jsdoc
jsdoc -c jsdoc.json
open doc/api/index.html
```

**Comment by Jerry-goodboy** [comment]
OK，已经成功生成文档，多谢大神 @firede 指点
