### ISSUE TITLE
使用echarts.graphic.Sector 添加的图形 为什么不是扇形呀  

### ISSUE THREAD

**Issue by anyushan** [ecomfe/zrender#184]
var _zr= myChart.getZr();

  _zr.add(new echarts.graphic.Sector

       ({
           shape: {
               cx: 330,
               cy: 330,
               r0: 30,
               r: 100,
               startAngle: 0,
               endAngle: 90,
               clockwise: true
           }, style: {
               stroke: '#d14a61',
               color: '#d14a61',
               brushType: 'both',
               fill: '#d14a61',

           },
           zlevel:0,
           z: 10001
       }));

**Comment by pissang** [comment]
那是啥？

**Comment by anyushan** [comment]
圆环行      并且环里还有其他图形     这儿怎么不能插图

**Comment by anyushan** [comment]
echarts是标签式引用

 myChart = echarts.init(document.getElementById('main'),theme);

**Comment by pissang** [comment]
startAngle, endAngle 是从 0 到 Math.PI * 2

**Comment by anyushan** [comment]
谢谢  ！
