### ISSUE TITLE
用zrender绘制的图，加了点击事件，在IE8下出现兼容问题

### ISSUE THREAD

**Issue by forzmfever** [ecomfe/zrender#187]
在IE8下，如果点击zrender绘制的图片，会出现重影。

**Comment by forzmfever** [comment]
在给zrender绘制的图片加载了点击事件之后。

**Comment by pissang** [comment]
有具体代码么？

**Comment by forzmfever** [comment]
是这样的，我用zrender渲染的图，然后页面的下方是echarts渲染的图。echarts的datazoom获取的数据用来给zrender渲染。zrender画的数据，有的线是可以点击的，并带着数据，显示详情。代码太多了.。。。贴个zrender的代码。
var verticalLine = new LineShape({
								shape: {
										x1: basePos.x1,
										y1: basePos.y1,
										x2: basePos.x1,
										y2: basePos.y1 + height
								}, style: {
										stroke: color
								}
						});
						verticalLine.data = lastData.id;
						verticalLine.on('click', function (event) {
								$("#standard-line").show().css({left: event.event.screenX});
								page.initDetail(this.data, detailMap, dataMap, itemIndex, true);
						});
						zr.add(verticalLine);

**Comment by forzmfever** [comment]
不知道是不是echarts和zrender同时存在一个页面，会不会有影响。我用requirejs加载的

**Comment by forzmfever** [comment]
估计跟我用的比较复杂有关。
