### ISSUE TITLE
在IE下, 初始化zrender失败导致echart图表无法显示

### ISSUE THREAD

**Issue by shikelong** [ecomfe/zrender#189]
## 环境
- windows 10
- ie 11
- "echarts": "^3.1.10",
## 浏览器报错

···bash
 SCRIPT65535: Invalid calling object

```

报错点 Animation.js (181,1)

···js

 start: function () {
            var self = this;

            this._running = true;

            function step() {
                if (self._running) {

                    requestAnimationFrame(step);

                    self._update();
                }
            }

            this._time = new Date().getTime();
            requestAnimationFrame(step);
        }

```

运行requestAnimationFrame这个方法的时候就会报错

谢谢。

**Comment by pissang** [comment]
我无法在 IE 11 上复现这个问题，你看下是不是有其它库覆盖掉了 requestAnimationFrame 这个方法

**Comment by shikelong** [comment]
[IE11 does not like it when requestAnimationFrame is called without window context](https://github.com/component/raf/pull/9)

恩 谢谢 我看看。

**Comment by shikelong** [comment]
恩 应该是其他库的原因 我在没有其他ui库的纯净环境下试了试是可以再ie11上出来的。

**Comment by shikelong** [comment]
https://msdn.microsoft.com/library/gg622930(v=vs.85).aspx

使用 window.requestAnimationFrame(step) 调用就没有问题了。
         使用requestAnimationFrame(step)调用会报错。

**Comment by shikelong** [comment]
使用 requestAnimationFrame=window.requestAnimationFrame.bind(window) 即可修复这个问题

**Comment by shikelong** [comment]
这个问题确实挺诡异的 我引用的其他库没有重写这个原生方法的

**Comment by shikelong** [comment]
![request](https://cloud.githubusercontent.com/assets/4499997/15890479/4fed8c88-2da2-11e6-9465-d8cf441d2f04.PNG)

**Comment by shikelong** [comment]
建议修改zrender这块的代码以增强在ie下的兼容性。 使用 requestAnimationFrame=window.requestAnimationFrame.bind(window) 来写的话不适应与js的严格模式。

**Comment by shikelong** [comment]
https://www.bountysource.com/issues/8152579-scroll-not-working-on-ie11

**Comment by kinglywork** [comment]
当webpack的config中devtool设置为含有eval时，可以重现问题

https://github.com/zloirock/core-js/issues/62

**Comment by airwin** [comment]
感谢分享，遇到了同样的问题

**Comment by ChaoYuLeo** [comment]
万分感谢，我也遇到了同样的问题。

**Comment by tongjun741** [comment]
遇到了同样的问题,关注中

**Comment by Roscoe93** [comment]
同样的问题，使用eval-source-map,requestAnimationFrame会报错

**Comment by Neilxzn** [comment]
同样遇到这样的问题关注中

**Comment by pissang** [comment]
赞 @shikelong

**Comment by nianhua110** [comment]
如何解決的呢，我用的echarts-for-react 依然存在這個問題。

**Comment by DanielWLam** [comment]
@shikelong 你那方法也太投机了吧，人家requestAnimationFrame本身做了浏览器兼容性处理，你倒好，直接window.requestAnimationFrame？

**Comment by shikelong** [comment]
@DanielWLam 我没有细看zrender的代码。具体怎么解决这个问题当然是看pissang怎么改。

至于我们的临时的解决方式。 webpack devtools的配置中不要使用eval选项即可。

**Comment by 100pah** [comment]
另外记录下这个解答链接：<http://www.foreverpx.cn/2017/03/04/echarts_webpack_ie/>
