### ISSUE TITLE
RectText缩放无效

### ISSUE THREAD

**Issue by ko300** [ecomfe/zrender#217]
RectText不跟随图形scale的来缩放大小，自己每个图形加了Text来重新算位置，比较麻烦。
有什么好的建议来解决这个问题吗？

**Comment by ko300** [comment]
textTransform为ture能解决这个问题，感谢

**Comment by ListenToMee** [comment]
新版没有textTransform，实现该功能代码如下，主要是local字段的配置：
`textContent: new ZRText({style: {text:’1111’}}),
      textConfig: {position: 'insideLeft', local: true},`
