### ISSUE TITLE
如何在一个元素的单击事件里操作/获取其他元素

### ISSUE THREAD

**Issue by liangyj021** [ecomfe/zrender#224]
想在一个元素的单击事件中，设置其他元素的样式，或做删除操作。比如一组圆圈，只有一个处于单选状态，这样的效果

**Comment by liangyj021** [comment]
在 `zr.storage._elements` 里

**Comment by 100pah** [comment]
不要直接使用 `_elements`。
可以使用：`zr.storage.get(elId)`
