### ISSUE TITLE
zrender交流群，有兴趣的加进来，技术讨论。

### ISSUE THREAD

**Issue by codeex** [ecomfe/zrender#230]
<a target="_blank" href="//shang.qq.com/wpa/qunwpa?idkey=5ff6b926bec736446416a4a7bd4702f3a37ccbce65731ac2af1d1e61994c46cf"><img border="0" src="//pub.idqqimg.com/wpa/images/group.png" alt="CodeEx" title="CodeEx"></a>

**Comment by NinjaJin** [comment]
群号多少啊？链接没用

**Comment by es3154** [comment]
链接无效
