### ISSUE TITLE
Uncaught TypeError: Cannot read property 'delRoot' of null

### ISSUE THREAD

**Issue by hustcc** [ecomfe/zrender#234]
网络原因没法上传图片，所以只能一文字来表示了。

[http://git.hust.cc/echarts-for-react/](http://git.hust.cc/echarts-for-react/#/?_k=280rj1) 这个地址中 Echarts theme 和 Dynamic chart 图表随意切换的时候，会出现这个异常。

console 错误信息为：

```
Uncaught TypeError: Cannot read property 'delRoot' of null
    at ZRender.remove (bundle.js:43657)
    at ECharts.echartsProto.hideLoading (bundle.js:26846)
    at bundle.js:98821
```

对应的代码（所属 ZRender.prototype）是：

```js
               /**
	         * 删除元素
	         * @param  {module:zrender/Element} el
	         */
	        remove: function (el) {
	            this.storage.delRoot(el); // 这里出的异常。
	            this._needsRefresh = true;
	        },
```

**Comment by pissang** [comment]
是不是 dispose 后继续使用了？

**Comment by hustcc** [comment]
哦哦，好像是的，在这个 [demo](http://git.hust.cc/echarts-for-react/#/echarts/loading?_k=cdowpe) 中，有一个定时器，切换的时候，unmount 的时候 dispose 了。
