### ISSUE TITLE
demo怎么还是2.x版本的？

### ISSUE THREAD

**Issue by chordmo** [ecomfe/zrender#241]
万年不更新的节奏。
http://ecomfe.github.io/zrender/index.html

![image](https://cloud.githubusercontent.com/assets/8435726/26516872/4966c260-42c0-11e7-823b-53e7414a4198.png)

**Comment by Ivorzk** [comment]
赞同 怪不得我就说怎么按照案例居然用不了，原来官网都是2.1.0的api！

**Comment by Kelier** [comment]
同遇到，试问新的api怎么用？

**Comment by Ovilia** [comment]
新的文档正在开发中~

**Comment by Ovilia** [comment]
文档和教程已上线 https://ecomfe.github.io/zrender-doc/public/
后面还会补充更多的教程和例子。
