### ISSUE TITLE
能否考虑支持一下typescript？

### ISSUE THREAD

**Issue by RichardWzr** [ecomfe/zrender#246]
如题，能否给出ts的兼容方案？

**Comment by Jianru-Lin** [comment]
同意。其实 zrender 非常适合用 TypeScript 重写。至少，也可以考虑提供类型定义文件。

**Comment by dream1009** [comment]
是啊，zrender 挺好用的，要是支持 ts 就更好了。

**Comment by Ovilia** [comment]
目前我们已完成了 zrender 的 ts 重构，在 next 分支，预计下一个大版本的时候正式引入。

**Comment by dream1009** [comment]
下一个版本预计什么时候发布呢

**Comment by beetaa** [comment]
@Ovilia ts 重构众望所归，谢谢.

**Comment by Ovilia** [comment]
@dream1009 目前只能说今年，更具体的日期还没有确定
