### ISSUE TITLE
echarts2下的工具方法在echarts3下怎样体现

### ISSUE THREAD

**Issue by Missyanwen** [ecomfe/zrender#248]
由于版本升级在echarts2下用这个
window.zrender.tool.area.isInsidePolygon()
方法可以访问，但是echarts3下是报错的，这样在echarts3下是怎么访问的？？？

**Comment by Ovilia** [comment]
文档和教程已上线 https://ecomfe.github.io/zrender-doc/public/
后面还会补充更多的教程和例子。
