### ISSUE TITLE
Which license is this repository used?

### ISSUE THREAD

**Issue by sufuf3** [ecomfe/zrender#250]
Hi @pissang , 
We are cdnjs team, we're going to host this library.

I see the content of license which in README.md is as same as [BSD-2-Clause](https://spdx.org/licenses/BSD-2-Clause), but I saw the license show `BSD-3-Clause` from https://libraries.io/npm/zrender and https://libraries.io/bower/zrender.

The [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause) is different from BSD-2-Clause due to the line --> `3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.`

Could you tell me Which license is this repository used? 

If you have any suggestions, please let me know.
Thank you.

cdnjs/cdnjs#11457

**Comment by pissang** [comment]
Hi @sufuf3 .

Thanks for noticing us the license problem. It should be same with [ECharts](https://github.com/ecomfe/echarts/blob/master/LICENSE). which is BSD-3-Clause. I will update it later.

**Comment by sufuf3** [comment]
@pissang Thank you.
