### ISSUE TITLE
如何绘制竖排文字

### ISSUE THREAD

**Issue by AquariusCoder** [ecomfe/zrender#252]
不能用旋转，

要
像
这
样

如何实现呢？

**Comment by AquariusCoder** [comment]
已找到答案：

使用 '我\n是\n竖\n排\n文\n字'

使用 style.textVerticalAlign 属性,可以设置竖排文字对齐

**Comment by Q-Xie** [comment]
如果有英文单词呢？直接每个字符都竖排显示就有点不好看了~
