### ISSUE TITLE
textRotation 属性

### ISSUE THREAD

**Issue by selfXin** [ecomfe/zrender#253]
如何设置文字属性旋转的中心点，测试一直以画布的左上角为中心旋转，请问这个如何解决呢？

**Comment by Ovilia** [comment]
可以设置 origin：https://github.com/ecomfe/zrender/blob/master/src/mixin/Transformable.js#L56
https://github.com/ecomfe/zrender/blob/master/src/mixin/Transformable.js#L236

**Comment by selfXin** [comment]
origin不起作用，他应该和rotation有关，与textRotation好像无关，

**Comment by 100pah** [comment]
目前，`textRotation` 是以 `text` 所隶属于的 `el` 的 `position` 为中心旋转。

**Comment by selfXin** [comment]
@100pah 解决了，我 shape上的cx,cy设置了初始值，所以没看出来，thank you
