### ISSUE TITLE
能否更新一下文档？

### ISSUE THREAD

**Issue by zuoliang0** [ecomfe/zrender#257]
文档已经很老旧，最后一次更新貌似是2015年。
希望团队更新一下。谢谢

**Comment by Jianru-Lin** [comment]
确实。zrender 写的很不错，但是文档、构建方式、测试方面都不太完善。如果能解决这些问题，相信 star 破万不是不可能。

**Comment by pissang** [comment]
谢谢肯定，文档更新已经在计划内

**Comment by Kelier** [comment]
加油！学生党可以帮忙翻译！

**Comment by Ovilia** [comment]
@Kelier 赞！我们现在需要中译英的人手，感兴趣吗？

**Comment by Kelier** [comment]
@Ovilia 回复晚了抱歉，没有问题，我可以试试！

**Comment by Ovilia** [comment]
@Kelier 感谢！

项目在 https://github.com/ecomfe/zrender-doc
你可以 fork 一下，然后提 pull request。
中文部分已经完成了，在 `src/_api_zrender` 和 `src/_api_zrender_instance`。

你可以先试着跑起来，然后增加一个 `src/_api_zrender_en` 和 `src/_api_zrender_instance_en`，把 `src/_config.yml` 下的 `collections` 改为 `api_zrender_en` 和 `api_zrender_instance_en` 即可编译英文的。

你可以按字母顺序，根据自己的精力翻译，不求多，但是要确保质量。提完 pull request 我们也会 review 一下再合入的。

如果还有什么问题，可以在 https://github.com/ecomfe/zrender-doc/issues 交流。再次感谢~~

**Comment by Kelier** [comment]
okay，我晚上看下 @Ovilia

**Comment by Ovilia** [comment]
文档和教程已上线 https://ecomfe.github.io/zrender-doc/public/
后面还会补充更多的教程和例子。
