### ISSUE TITLE
能否实现文字透视功能?

### ISSUE THREAD

**Issue by zuoliang0** [ecomfe/zrender#259]
![image](https://user-images.githubusercontent.com/8434253/28952471-e97882f6-7903-11e7-907f-8a106585edf6.png)
大概就是这样

**Comment by Jianru-Lin** [comment]
@zuoliang0 zrender 只是一个 2d 库。如果要得到这样的效果，最好的方式应该使用 3d 库。否则只能通过一些变换来近似。但效果和性能都不理想。

**Comment by zuoliang0** [comment]
是的，我前几天研究了很久也没有办法，所以用css3实现了一下
