### ISSUE TITLE
不能直接使用Rect绘制平行四边形

### ISSUE THREAD

**Issue by f1194361820** [ecomfe/zrender#269]
我本来是希望绘制一个立方体的，绘制立方体时，不可避免的要绘制平行四边形。

我使用原生canvas API可以绘制出立方体，但是用zrender，设置transform 不管用，然后改用rotation，position, scala ，但是发现 rotation  只能用于坐标系整体旋转，但不能用于 x, y 分别旋转，从而导致不能做出平行四边形来。

**Comment by Ovilia** [comment]
用 Path 自己 extend

**Comment by f1194361820** [comment]
嗯嗯
