### ISSUE TITLE
性能牛逼的爆

### ISSUE THREAD

**Issue by mtsee** [ecomfe/zrender#274]
我测试了多个canvas框架，有国外的，zrender 完胜。希望能用es6进行重构。如果不介意，我愿意给作者设计新版的官方页面

**Comment by Ovilia** [comment]
谢谢~ 我们已经在着手官网的改版工作了，非常感谢您的支持！后面还会支持 SVG 渲染，敬请期待~

**Comment by pissang** [comment]
@mtsee 谢谢肯定，方便的话能跟我们分享下你的测试用例和结果数据么？
