### ISSUE TITLE
npm库中3.6.2版本的源码与github中tag:3.6.2的源码不一致

### ISSUE THREAD

**Issue by jaguarsy** [ecomfe/zrender#279]
<img width="254" alt="local" src="https://user-images.githubusercontent.com/2453013/30952383-48d3795e-a3ed-11e7-8174-7d40c2397076.png">
<img width="254" alt="remote" src="https://user-images.githubusercontent.com/2453013/30952386-49070292-a3ed-11e7-934c-48e309fc6019.png">

在mac下由于对大小写不敏感，打包不会出现问题。但是在linux下webpack打包会出现Cannot resolve 'file' or 'directory' ./Definable的错误。

**Comment by PanJiaChen** [comment]
same problem...

**Comment by pissang** [comment]
@jaguarsy @PanJiaChen 在 publish 前转换成 CommonJS 模块的时候处理有点问题，你们现在是有用到 SVG 渲染的模块么？

**Comment by jaguarsy** [comment]
@pissang 我是在更新echarts的时候发现的这个问题，项目里面应该是没有用到svg渲染。

**Comment by pissang** [comment]
@jaguarsy zrender 重新发布了 3.6.3，更新下试试？

**Comment by jaguarsy** [comment]
已经没问题了，辛苦了😄

**Comment by wangyaju** [comment]
同样使用echarts遇到  正在规避  就看到处理了  贊一个
