### ISSUE TITLE
什么时候能出一个系统的教程！！！！！

### ISSUE THREAD

**Issue by es3154** [ecomfe/zrender#285]

**Comment by Ovilia** [comment]
正在准备中

**Comment by es3154** [comment]
https://github.com/ecomfe/zrender-doc/tree/master/src/_api_zrender  这里面的文档看的差不多了

**Comment by Ovilia** [comment]
恩，打算等 zrender 网站、教程一起开发，所以还需要一段时间

**Comment by es3154** [comment]
刚看到bbox这个类这个文档上没有介绍，npm包下zrender/index.js里面没有引入

**Comment by ColinCLL** [comment]
这个好东西，文档居然和Echart文档差这么远。。。期待更新

**Comment by Ovilia** [comment]
文档和教程已上线 https://ecomfe.github.io/zrender-doc/public/
后面还会补充更多的教程和例子。

**Comment by ColinCLL** [comment]
先赞了再看~~

**Comment by es3154** [comment]
已赞
