### ISSUE TITLE
zrender 从3.6.3 升级到3.7.0 后引起Webpack uglify bug 

### ISSUE THREAD

**Issue by HuanxinHu** [ecomfe/zrender#293]
zrender 版本：3.7.0， Echarts 版本： 3.7.2
在项目源码引用Echarts 方式是 import Echarts from 'echarts'; 
从3.6.3升级到3.7.0后,  webpack uglify 报错，报错原因不能解析ES6语法.
去除uglify plugin, 项目build成功，但是上线后还是报错
<img width="977" alt="screen shot 2017-11-08 at 6 15 35 pm" src="https://user-images.githubusercontent.com/7131790/32585409-2ef2ffa6-c4b2-11e7-8a71-81c4e5ac8d82.png">
<img width="555" alt="screen shot 2017-11-08 at 6 15 45 pm" src="https://user-images.githubusercontent.com/7131790/32585411-31407478-c4b2-11e7-8efc-9660e6fcaf4e.png">

**Comment by Solitary-Z** [comment]
急等

**Comment by szrenwei** [comment]
升级后整个应用都挂了。。。Path.extend is not a function...怀疑是模块系统的问题，能不能测好后再发？

**Comment by shenzhirong** [comment]
嗯嗯，导入模块化的方式直接挂掉了

**Comment by weizs** [comment]
"dependencies": {
    "zrender": "3.6.1",
    "echarts": "3.7.1"
  }
先这样搞了

**Comment by shenzhirong** [comment]
请教一下大家  调用new Text()方法创建文本 为什么会报错：
![20171109144224](https://user-images.githubusercontent.com/5197159/32591959-961ed308-c55c-11e7-936c-57274324628c.png)

 zr.add(new Text({
            style: `{`
                x: 0,
                y: 0,
                text: '国国国国\n国国国国国\n国国国国国国',
                width: 50,
                height: 50,
                textFill: '#c0f',
                textFont: '18px Microsoft Yahei'
            },
            draggable: true
        }));

**Comment by weizs** [comment]
![image](https://user-images.githubusercontent.com/5949090/32593420-cd818628-c562-11e7-950e-98bd3b63506e.png)

![image](https://user-images.githubusercontent.com/5949090/32593411-c3304f6a-c562-11e7-87e0-0157b1ca39d0.png)

这个怎么破，我降级了貌似还不行

**Comment by weizs** [comment]
发现这样降级不行
`"dependencies": {
"zrender": "3.6.1",
"echarts": "3.7.1"
}`
因为使用的yarn，支持配置如下，好了
`"resolutions": {
    "zrender": "3.6.3"
  }`

**Comment by KidneyFlower** [comment]
@szrenwei 您好，请问您的问题解决了吗，我也遇到一样的问题，心态崩了...

**Comment by yangbinlovegis** [comment]
![image](https://user-images.githubusercontent.com/8787605/32600920-102d9124-c57c-11e7-822e-082fd4a09e44.png)
昨天还不报错，今天就报错了

**Comment by szrenwei** [comment]
@KidneyFlower  解决了，这个是因为 echarts 依赖的 zrender 被升级到 3.7.0 了，而 zrender 3.7.0 又把模块系统全部改成了 es6 module...解决办法就是 echarts 升级到 3.8.0, 然后 import echarts from 'echarts' 改为
```javascript
 import echarts from 'echarts'
```

**Comment by skypacer210** [comment]
同样因为这个问题，我们的前端服务构建出现问题，导致线上迟迟不能发布新版本，搞了整整一天。。。
@KidneyFlower 腰花兄，我们是这样解决的：直接在依赖zrender包之前强行依赖旧的版本：

 22     "zrender": "3.5.2",
 23     "echarts": "3.6.2",

**Comment by lincolnzhou** [comment]
我们也折腾了一下午，用npm的lock机制，直接将echats和zrender强制锁版本，才得以解决。

"echarts": "3.7.1",
"echarts-for-react": "^1.4.4",
"zrender": "~3.6.3"

**Comment by Stupidism** [comment]
用echarts-for-react的小伙伴们看@lincolnzhou的方案.
自己用的应该看@szrenwei的就行了~~~

**Comment by KidneyFlower** [comment]
@skypacer210 谢谢啦，昨天着急上线，也没来得及细想，干脆用script标签引入了echarts然后把之前的echarts指向了window.echarts，今天看了你们的解决方案觉得自己蠢萌蠢萌的hhhhh

同时也感谢 @szrenwei

**Comment by pissang** [comment]
我们在新发布的 3.8.2 中将 lib 下的重新转译成了 CommonJS 格式并且去掉了 __DEV__，应该解决了大家构建的兼容问题。非常抱歉新版本的模块系统给大家造成了这么大的麻烦。
