### ISSUE TITLE
请问如何使用zrender.Pattern对象?

### ISSUE THREAD

**Issue by stephenliu1944** [ecomfe/zrender#298]
感觉是设置到 Displayable 对象上, 但是没有找到 Displayable 对象对应设置 fillStyle 和 strokeStyle 的地方, 是在opts.style.fill和opts.style.stroke属性上设置吗? 能否给个Pattern是png图片的示例?

**Comment by pissang** [comment]
在 style.fill 上设置，pattern 的 image 属性必须是一个 Image 对象，不能是字符串

**Comment by stephenliu1944** [comment]
var image = new Image();
image.src = smileJPG;   // 图片大小为41x41
image.onload = (e) => {
              var pattern = new zrender.Pattern(image, 'repeat');            
              var shape = new zrender.Rect({
                shape: {
                    x: this.zr.getWidth() / 2,
                    y: this.zr.getHeight() / 2,
                    width: 41,
                    height: 41
                },
                style: {
                    text: 'xxxx公司',
                    fill: pattern,
                    textPosition: 'bottom'
                }
            });
            this.zr.add(shape);
};
请问我的图片大小为41x41, 设置的矩形宽高也是41, 但是这样绘制出来, 图片在矩形区域显示的位置不正确, 请问这里是要换算一下吗? 如何换算呢?

**Comment by beetaa** [comment]
@stephenliu1944 试试用 position 更改容器位置：

```js
var shape = new zrender.Rect({
    position: [this.zr.getWidth() / 2, this.zr.getHeight() / 2],
    shape: {
        x: 0,
        y: 0,
        width: 41,
        height: 41
    },
    style: {
        text: 'xxxx公司',
        fill: pattern,
        textPosition: 'bottom'
    }
});
```
