### ISSUE TITLE
Draggable 在设置 origin 后不可用

### ISSUE THREAD

**Issue by csvwolf** [ecomfe/zrender#337]
效果非常遭的 Draggable。我的目标是希望让 rotation 能绕着中心点旋转，不知道现在有什么解决方案吗？因为两者都是属性，所以没有办法保持 Draggable 和 rotation。

Bad Case：https://jsfiddle.net/csvwolf/1vpntvmo/

**Comment by csvwolf** [comment]
@pissang 似乎还没有发版 Emmmm

**Comment by pissang** [comment]
@csvwolf 在下一个版本

**Comment by csvwolf** [comment]
@pissang 你好，今天试用了一下，发现仍然存在这个问题，复现是将 origin: [x, y] x != y 的情况下，demo 中的 50, 50 是可行的，但是改成了 51, 49 就不行了

**Comment by csvwolf** [comment]
@pissang 你好，今天试用了一下，发现仍然存在这个问题，复现是将 origin: [x, y] x != y 的情况下，demo 中的 50, 50 是可行的，但是改成了 51, 49 就不行了
