### ISSUE TITLE
svg模块内textRotate修复bug后又引入新bug，相关提交：commit bef1891 

### ISSUE THREAD

**Issue by qqj1228** [ecomfe/zrender#358]
在 `commit bef1891` 这次提交中，是为了修复文字旋转过渡动画bug：fix(svg): text transform bug caused by textRotate。

但是，新增的代码中引入了新的bug，这次提交的437行

```
-        var rotate = -(style.textRotation || 0) * 180 / Math.PI;
-        attr(textSvgEl, 'transform', 'rotate(' + rotate + ','
-            + x + ',' + y + ')');
+        var rotate = -style.textRotation || 0;
+        var transform = matrix.create();
+        // Apply textRotate to element matrix
+        matrix.rotate(transform, el.transform, rotate);
+        setTransform(textSvgEl, transform);
```

`matrix.rotate(transform, el.transform, rotate);` 这个函数调用的第二个参数 `el.transform` 有问题

若用户没有设置过渡动画效果的话 `el.transform` 值为 `null` ，`matrix.rotate` 函数执行会报错：`Uncaught TypeError: Cannot read property '0' of null`

应该像这次提交的413行那样做一个判断，然后分情况处理。

版本号在4.0.3之后至今的版本都未修复这个bug。只要调用了svg的文字旋转功能的话都会受影响（包括旋转0度）

echarts从4.1.0开始使用了zrender v4.0.4，所以echarts从4.1.0开始的新版本也受此影响。

实际上我就是在使用4.1.0的echarts中 `showloading()` 函数时发现有此问题的，调用 `showloading()` 后会显示loading动画，在显示动画的每一帧里都会调用 `matrix.rotate` 函数使文字旋转0度。

使用zrender v4.0.3的echarts v4.0.4没有该问题。

**Comment by qqj1228** [comment]
echarts里的相关issue
https://github.com/apache/incubator-echarts/issues/8311
https://github.com/apache/incubator-echarts/issues/8341

**Comment by Nilegfx** [comment]
@qqj1228

Appreciate if you can explain the issue/solution in english as I am affected with this issue too.

**Comment by qqj1228** [comment]
@Nilegfx 
`commit bef1891` bring new bug, as the code block showing，line 437，
The second argument of function `matrix.rotate(transform, el.transform, rotate)` is wrong. 
`el.transform` is `null` if user didn't define rotation effect. Thus invoke `matrix.rotate` will throw exception:  `Uncaught TypeError: Cannot read property '0' of null`. 

My pr about this bug: https://github.com/ecomfe/zrender/pull/360

So you have two choices:
1. Using canvas instead of svg
2. Using echarts v4.0.4 which use zrender v4.0.3.

**Comment by Ovilia** [comment]
Fixed in https://github.com/ecomfe/zrender/commit/0cc622196d8665f40d02b6156450cc7a87fe3a67 for this bug, but SVG text still has other potential bugs and I'm working on it.
