### ISSUE TITLE
文字缩放问题

### ISSUE THREAD

**Issue by mtsee** [ecomfe/zrender#359]
在设置shape 是 zrender.Image的时候，设置了文字，文字不会因为缩放而缩放。如果单独加的 zrender.Text的时候，文字会跟着缩放而变大变小，可以固定文字大小吗？

**Comment by Ovilia** [comment]
这是个 bug，在 https://github.com/ecomfe/zrender/commit/0cc622196d8665f40d02b6156450cc7a87fe3a67 已修复，但目前还没有发版，可以自己编译使用。

根据[文档](https://ecomfe.github.io/zrender-doc/public/api.html#zrenderdisplayable)，应该是在设置了 `style.transformText` 为 true 的情况下文字才跟着一起缩放，默认值是 false。
