### ISSUE TITLE
画布放缩问题

### ISSUE THREAD

**Issue by leitinggit** [ecomfe/zrender#371]
我现在想通过鼠标的滚轮控制画布上所有元素的缩放，我的过程如下：
1.创建一个zoomable.js 并将js混入到Handler.js中，从而将zoomable中的放缩控制函数（_onMouseZoom）on到Handler.js的mousewheel事件中
2.因为zoomable.js是混入到Handler中的，所以可以获取storage实例，在storage中我增加了一个函数叫：updateGlobalScaleRatio，循环storage中的每一个element，根据鼠标的偏移量按照比例去修改每个element元素实例的globalScaleRatio
后来做下来发现，这个globalScaleRatio只对有放缩的元素起作用，对未放缩的元素不起作用，那么这里我想做全画布的放缩，应该怎么做呢？

**Comment by leitinggit** [comment]
我这里用ts写的，其实都一样，Zoomable.ts文件如下：
`import Storage from "../Storage";

class Zoomable {

  initZoomable() {
    (<any>this).on('mousewheel',null, this._onMouseZoom, this)
  }

  _onMouseZoom(event:any) {
    let delta = event.wheelDelta || -event.detail
    let zoomValue = delta / 10
    let storage = <Storage>(<any>this).storage
    storage.updateGlobalScaleRatio(zoomValue)
  }

}
export default Zoomable`

Storage里增加的updateGlobalScaleRatio函数如下：
`updateGlobalScaleRatio(zoomValue: number) {
    let roots = this._roots
    let rootsLen = roots.length
    for(let i =0; i < rootsLen; i++){
      roots[i].globalScaleRatio = Math.max(0.2,Math.min(zoomValue, 5))
    }
  }`

**Comment by leitinggit** [comment]
哪位老铁能帮忙看看呢？

**Comment by yuqianma** [comment]
我觉得你只要用一个group包裹全部element
改变这个group的scale就行了

**Comment by leitinggit** [comment]
@yuqianma 谢谢您，问题已经按照您提供的方法解决了。

**Comment by zhouhuan0910** [comment]
想请问一下，在缩放时，节点文字的间距怎么同时缩放呢，因为我设置了textPosition属性
