### ISSUE TITLE
Are you planning to support OffscreenCanvas?

### ISSUE THREAD

**Issue by liyuanqiu** [ecomfe/zrender#375]
OffscreenCanvas is available without a flag in Chrome 69. It is also in development in Firefox. It can positively influence web app’s performance.

[API Doc: https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas)

[Tutorial: https://developers.google.com/web/updates/2018/08/offscreen-canvas](https://developers.google.com/web/updates/2018/08/offscreen-canvas)

Hope you to consider this new feature.

**Comment by liyuanqiu** [comment]
@leitinggit 
I don't think "zlevel" means `OffscreenCanvas`. Could you show me the code which uses `window. OffscreenCanvas`?

**Comment by leitinggit** [comment]
看你名字，应该会讲中文，中文沟通吧，你可以看看下面链接：
https://blog.csdn.net/qq_34309704/article/details/81478695
如果还有问题，我们进一步沟通。

**Comment by liyuanqiu** [comment]
@leitinggit 
是的，母语是中文，只是习惯在这样的平台上讲英语，以免外国朋友搜索到这个页面确看不懂。
Your article is similar to [Canvas 最佳实践（性能篇）作者: 叶斋 发表于: 2016-02-22](http://taobaofed.org/blog/2016/02/22/canvas-performance/)
I'v read this article before, it's just a trick of `context.drawImage`, really useful to improve the performance.
But both of the two articles are not talking about `window.OffscreenCanvas` or something about rendering a canvas in `Web Worker`. Maybe you haven't read my hyperlinks in issue. I still think we are not talking about the same thing.

**Comment by srowhani** [comment]
Also wondering this as well, are there any plans for this?

**Comment by Ovilia** [comment]
Sorry, no current plan to support this.

**Comment by skortchmark9** [comment]
I was able to get some basic echarts workingg with offscreen canvas like so:

```javascript
// main.js
const canvas = document.getElementById('main');
const offscreen = canvas.transferControlToOffscreen();

const worker = new Worker('worker.js');
worker.postMessage({ canvas: offscreen }, [offscreen]);

// worker.js
self.importScripts('echarts.js')

onmessage = function(evt) {
	const canvas = evt.data.canvas;

	echarts.setCanvasCreator(function () {
		return canvas;
	});

	var myChart = echarts.init(canvas);
};
```

I'd definitely recommend y'all continue to explore it.
