### ISSUE TITLE
4.0.5版本调整图形透明度无效bug      attr(style.opacity)

### ISSUE THREAD

**Issue by wenshanshan** [ecomfe/zrender#379]
4.0.4没问题
4.0.5group中add多个图形,分别调整透明度时 ,无反应(TEXT有此问题,Image似乎没有)

还有两个神奇的现象
1.如果text的z>image的z
调整image的opacity时,text的opacity会跟着变

2.opacity调整到某些数值时,比如 0.31,0.51,0.81(不固定,好像x1的比较多)
会出现opacity=1的效果

害我找了5个小时bug

**Comment by wenshanshan** [comment]
zr.add(shape)
g.add(shape)
均有此问题

**Comment by es3154** [comment]
我刚升级，之前好好的效果，本来图层在上面的，现在跑下面了，透明度也有问题

**Comment by Ovilia** [comment]
@wenshanshan 提供下能复现的简单代码？

**Comment by Manifold7** [comment]
同遇到这种bug而且和z无关，影响了不止Text。调整z后依旧有问题。改变绘制顺序可以改善，但是没有解决。

**Comment by Manifold7** [comment]
` <div id="main" style="background: #333"></div>
    <script type="text/javascript">
	    // 初始化zrender
        var main = document.getElementById('main');
        var zr = zrender.init(main);



        var w = zr.getWidth();
    		var h = zr.getHeight();
	

	logeY = new zrender.Image({
        style: {
        		image:'https://23shiji.github.io/yipolis-map/map/plugins/logo/logo.svg',
			height:100,
			width:71.5,
			x:w-90,
			y:h - 125,
			z:1,
			opacity:0.5
        },
		onmouseover: function () {
        		logeY.attr('style',{opacity:1});
        },
		onmouseout: function () {
        		logeY.attr('style',{opacity:0.5});
        }
    });
	logeY.on('click',function(){
		 window.open("http://wiki.23shiji.net/wiki/index.php/%E9%A9%BF%E5%AE%81%E5%85%B1%E5%92%8C%E5%9B%BD"); 
	});
    zr.add(logeY);	

    var t1 = new zrender.Text({
        style: {
            text: '23世纪',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fontSize: 200,
            fontFamily: 'Lato',
            fontWeight: 'bolder',
            textFill: '#0ff',
            blend: 'lighten',
			z:0
        },
        position: [w / 2 + 5, h / 2]
    });
    zr.add(t1);

    var t2 = new zrender.Text({
        style: {
            text: '23世纪',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fontSize: 200,
            fontFamily: 'Lato',
            fontWeight: 'bolder',
            textFill: '#fff',
            blend: 'lighten',
			z:0
        },
        position: [w / 2, h / 2],
    });
    zr.add(t2);`
@Ovilia

**Comment by Ovilia** [comment]
这个问题已修复，请等下一次发版~
