### ISSUE TITLE
请问画布中指定某个shape独立缩放是基于什么原理? 

### ISSUE THREAD

**Issue by stephenliu1944** [ecomfe/zrender#382]
是使用drawImage吗? 还是把shape切出来放到offscreenCanvas调整好缩放比例后再重新画到画布上? 还是其他方式?

**Comment by Ovilia** [comment]
shape 的缩放就是记录了 shape 的缩放，然后调用 ctx.transform 分别绘制每个图形，画另一个图形的时候重新 transform。
