### ISSUE TITLE
当渲染为canvas时，如果画布尺寸太大，【在谷歌浏览器下】拖放元素时比较卡，CPU且高。

### ISSUE THREAD

**Issue by TinyPHP** [ecomfe/zrender#385]
当渲染为canvas时，如果画布尺寸太大，【在谷歌浏览器下】拖放元素时比较卡，CPU且高。
其它浏览器正常，svg正常。

**Comment by TinyPHP** [comment]
也不是非常大，

> 数据量很大么？代码方便提供下么？

也不是非常大，如height:1600    width:1600这样的尺寸就会出现，再大就更卡了，小尺寸正常。

**Comment by TinyPHP** [comment]
> 数据量很大么？代码方便提供下么？

测试后，回复个信息罢，别什么也不说。是什么情况总有有个结果吧？

**Comment by Ovilia** [comment]
没有感觉到卡。
建议在 Chrome Performance 面板调试下，看看费时的是什么操作。

**Comment by TinyPHP** [comment]
**改成8000px 你就应该能很明显的感觉到了，1600px只能算是很小的卡，不仔细的话，可能不是很觉察的到。**

**Comment by Ovilia** [comment]
8000px 的 canvas……你啥都不做都会卡的……
<img width="1436" alt="2018-11-22 5 44 12" src="https://user-images.githubusercontent.com/779050/48894709-5c804400-ee7e-11e8-936c-117efbcf736d.png">

调试方法也教给你了，时间都花在绘制上了，跟 js 部分没关系。就是确实 canvas 太大了。
理论上可以试一下 SVG，但这个 case 的 SVG 似乎有 bug，如果不是 Pin 图形的话，换成 SVG 试试。

**Comment by TinyPHP** [comment]
> 8000px 的 canvas……你啥都不做都会卡的……
> <img alt="2018-11-22 5 44 12" width="1436" src="https://user-images.githubusercontent.com/779050/48894709-5c804400-ee7e-11e8-936c-117efbcf736d.png">
> 
> 调试方法也教给你了，时间都花在绘制上了，跟 js 部分没关系。就是确实 canvas 太大了。
> 理论上可以试一下 SVG，但这个 case 的 SVG 似乎有 bug，如果不是 Pin 图形的话，换成 SVG 试试。

问题是其它浏览器是正常的，只有谷歌浏览器这样。8000px在其它浏览器下没问题的。

**Comment by HawthornXU** [comment]
没有必要有8000px的canvas吧 写个虚拟滚动
