### ISSUE TITLE
Latest commit of syntax fixed cause mistake when drawing arc in PathProxy & Path 

### ISSUE THREAD

**Issue by Cmen117696** [ecomfe/zrender#398]
![image](https://user-images.githubusercontent.com/15258308/50194241-ef74a700-0374-11e9-9a39-33d9b52d69a0.png)

![image](https://user-images.githubusercontent.com/15258308/50194251-fbf8ff80-0374-11e9-8cf0-5900a7fd8a45.png)

**Comment by Ovilia** [comment]
Hi. Could you please explain what's wrong here?

**Comment by Cmen117696** [comment]
It seems lint tool has removed  the statement of unused variable 'psi' , and that cause local variable 'i' unable to automatically increase.

**Comment by yuqianma** [comment]
https://github.com/ecomfe/zrender/commit/2e324ec59d11dba59edfff13f751dddf0c8cfe8d#diff-7e6fb909a0ebb7164114ab3c372e0c63L305

https://github.com/ecomfe/zrender/commit/2e324ec59d11dba59edfff13f751dddf0c8cfe8d#diff-3300493578eec46df62436db18eb203bL632

Did you fix them with eslint?

**Comment by Ovilia** [comment]
@Cmen117696 Seems to be correct. @deqingli will have a look.

**Comment by Ovilia** [comment]
Merged.
