### ISSUE TITLE
请问怎么清除一个group中的元素

### ISSUE THREAD

**Issue by zhouhuan0910** [ecomfe/zrender#400]
我在使用zrender绘制一个树形结构，父节点有一个收缩按钮的功能，点击收缩的时候想要清除画布重新绘制，但是我把所有的元素都添加到了group中，使用group的目的是为了控制缩放和拖动。
但是如果不使用group，直接把元素add到zr中是可以实现的，所以想问一下group有没有类似zr.clear()的功能，谢谢

**Comment by yuqianma** [comment]
removeAll
可以自己看源码

**Comment by Ovilia** [comment]
https://ecomfe.github.io/zrender-doc/public/api.html#zrendergroup 文档在这里
