### ISSUE TITLE
官方文档上写的 字体样式配置根本不生效

### ISSUE THREAD

**Issue by Ivorzk** [ecomfe/zrender#411]
以下属性，在项目实战中，无法生效，

opts.style.textLineHeight | number | 0 | 文字行高。

demo 测试地址

http://test.suwis.com/zrender/zrender.bug.html

这些属性根本就不生效好吧，这个影响很大，请尽快修复！我还没有全部核查，请贵公司好好做产品

**Comment by Ovilia** [comment]
就事论事地讲，你怎么用的代码不贴出来，就说配置不生效，让别人怎么帮你解决问题呢？你试过哪些方法，想要什么效果，问题是什么？这些都没有，你到底是想来解决问题，还是寻找发泄的呢？

就算是有 bug，或者文档写得不好，这是一个开源项目，你可以自己对它进行改进，帮助更多人。
就算你不愿意自己看源码，至少可以态度友好一点，「请教」其他开发者怎么使用，或者怎么排查是不是 bug。这要求不过分吧？
这样没头没脑地就说这些话，不知道你有没有心情变好点，反正对你解决问题是没有帮助的。

如果你愿意，可以改进一下 issue 的具体描述。如果还是这么不友善的话，为了维护社区的友善环境，我将关闭这个 issue。

**Comment by Ivorzk** [comment]
首先，如果是我言语过当，那我说声对不起！
为了更好描述问题，我特意做了一个测试地址，点开测试地址，即可看到问题的描述
http://test.suwis.com/zrender/zrender.bug.html
我的目的是为了解决问题，也不是来这宣泄心情，我没那闲工夫
最后建议zrender的文档中，可否加入代码示意，这样对开发者会比较友好

**Comment by Ovilia** [comment]
就是说你上面提的四个属性只有 `textLineHeight` 没生效是吧？

**Comment by Ivorzk** [comment]
是的！暂时是这样！后期后问题会继续反馈

**Comment by Ivorzk** [comment]
还请贵公司尽快修复，这个问题，感激不尽！

**Comment by Ovilia** [comment]
已修复，等上线吧。急用的话，clone 下项目，然后：
```bash
git fetch
git checkout feature/textLineHeight
npm i
node build/build.js
```

**Comment by 100pah** [comment]
目前只有 `richText` 支持 `lineHeight`。
不过可以把 plain text 也加上 `lineHeight`。

**Comment by Ovilia** [comment]
是 `textLineHeight`
