### ISSUE TITLE
经过测试，zrender.Displayable   中的 opts.style.textLineHeight 已经生效，但尚未同步到npm中

### ISSUE THREAD

**Issue by Ivorzk** [ecomfe/zrender#413]
1.首先感谢贵公司这么及时的修复bug
2.但是呢这个新版尚未同步到npm中，目前我们是通过手动将github的代码替换到项目中的，node_modules 文件夹，如果npm也同步仓库更新那就太好了！

**Comment by yuqianma** [comment]
I wonder whether I entered an after-sales forum...

**Comment by Ovilia** [comment]
Not released yet.
