### ISSUE TITLE
请问这个解法是因为第一时间想到“国字脸”吗

### ISSUE THREAD

**Issue by AntiMoron** [ecomfe/zrender#418]
![image](https://user-images.githubusercontent.com/6587734/51172913-45465b80-18ef-11e9-856b-a0478b423f0b.png)

**Comment by AntiMoron** [comment]
https://github.com/ecomfe/zrender/blob/1bf50b4ffadc6214d6e5abe0f47d5a880c64f56a/src/contain/text.js#L364

确实没有好的measure方法，浏览器不会把height返回回来..我现在的做法是：

```javascript
    /**
     * 行高
     */
    public get lineHeight(): number {
        let height = 30;
        switch (this.measurement) {
            case 'px':
                height = this.size;
                break;
            case 'pt':
                height = this.size * 1.3281472327365; // 不咋准，总是大一块..因为总是拿不到baseline偏移
                break;
            default: break;
        }
        return height;
    }
```

**Comment by Ovilia** [comment]
用“国”字是因为这是一个可以认为是占满可用空间的字，当然，也不是绝对……
baseline 偏移不是拿不到（`measureText` 可以获得 `TextMetrics.fontBoundingBoxDescent`），而是实际测量下来 `measureText` 结果里的这几个值都不是很准确。我理解这是由于字体文件里的这些值不总是准确的，或者说字体设计师不总是按这个值来设计字体的。
如果你想要非常精确的结果，可以在 Canvas 上绘制文字后，[剪裁掉空白的 Canvas](https://github.com/Ovilia/font2img.js/blob/master/font2img.js#L192) 获得实际的宽高。当然，这种方法只适用于获得确定文字的宽高，而不能获得所有文字的最大宽高。

**Comment by AntiMoron** [comment]
web canvas的color components保证是4个(r,g,b,a)的吗？会不会有可能只是灰度图
我看裁剪空白canvas是每隔4个一找。

**Comment by AntiMoron** [comment]
感谢
