### ISSUE TITLE
Animator.prototype.when(time, props) ， 关键帧执行时刻不准确问题

### ISSUE THREAD

**Issue by zfirsty** [ecomfe/zrender#428]
在实际使用中，发现通过when（）设置的多个帧动画，在有easing的情况下，不能保证那个time的时刻下就是那个帧（Props）。
通过阅读源码，发现除了开始（初值）和结束（最大的Time帧），中间设置的time实际是百分比的一个概念，实际的执行时刻取决于Easing，当且仅当Easing为“Linear”时，这个实际的执行时刻才和设置的time值相等。
希望能够得到解决，或在文档中标注。

**Comment by yuqianma** [comment]
你可能没理解easing的作用，可以类比物理，比如加速度。如果一个物体按加速度运行，time和props的关系当然不是线性（linear）的。
