### ISSUE TITLE
关于文字垂直居中的问题?

### ISSUE THREAD

**Issue by webliving** [ecomfe/zrender#436]
请问: 文字垂直居中怎么设置? textVerticalAlign: 'middle', 和 position 我都设置了合理的值 , 水平居中似乎看上去还行,  但垂直居中还是不对, 是和文字baseline 什么有关系吗?

**Comment by yuqianma** [comment]
文字绝对的垂直居中比较难搞，和字体还会有关系
按照计算的height / 2偏移，视觉上可能不是居中
最好提供一个例子看一下

**Comment by webliving** [comment]
😄 我的 position 是按照 height / 2 设置的, 但总感觉有那么些偏差, 我再研究看看.
