### ISSUE TITLE
cpu占用问题

### ISSUE THREAD

**Issue by somax** [ecomfe/zrender#44]
发现requestAnimationFrame非常占用cpu,觉得可以在不需要动画的时候停止,所以
我在代码中加了stopAnimation和startAnimation,如果这样没有问题的话,希望在后续版本中加入类似功能接口.
或者可以做到智能侦测?!
            self.startAnimation = function () {
                animation.start();
            }
            self.stopAnimation = function () {
                animation.stop();
            }

**Comment by unlimit-ed** [comment]
目前这个 issue 有什么办法么??
requestAnimationFrame 可以做到 图表改变的时候 调用,图表没有任何动作的时候 stop 么?
@pissang @somax

**Comment by unlimit-ed** [comment]
直接 close 了?  当前版本还是会有 echarts 图形过多的时候(10+个),  requestAnimationFrame 比较消耗 CPU 的问题.  @pissang

**Comment by pissang** [comment]
没有动画的时候 requestAnimationFrame 跟图形数量没啥关系

**Comment by xushimin** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>requestAnimationFrame循环测试</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   
</head>
<body>
    <script type="text/javascript">
    function _startLoop() {

        function step() {
            requestAnimationFrame(step);
        }

        requestAnimationFrame(step);
    }

    _startLoop()
    </script>
</body>
</html>
你可以看看这种情况的requestAnimationFrame占用，已经有4%-5%了
