### ISSUE TITLE
svg渲染下rich失效

### ISSUE THREAD

**Issue by caoxiaoxiaoming** [ecomfe/zrender#446]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Text</title>
 
	 <script src="../dist/zrender.js"></script>
	
	
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body style="margin:0">

   
    <div id="main" style="width:1200px;height:2200px;margin:0;"></div>

    <script type="text/javascript">

    var zr = zrender.init(document.getElementById('main'),{
		renderer: "svg"
	});

	zr.add(new zrender.Text({
         style: {
             x: 200,
             y: 300,
             text: [
                 'x: 200, y: 300{j|这行指定了 lineHeight 100px (vertical top)}所以比较宽裕{k|vertical bottom}',
                 '{l|textPadding: [10, 20]}{m|textPadding: [10, 20, 30, 40], vertical: top}{o|width100}{n|width100}',
                 '默认样式red 18px',
                 '{a|富文本，样式a没定义}',
                 '{b|默认字体大小但有阴影}默认样式18px{c|绿色 30px}{b|这句非常非常长最长。阴影样式。中间有\n换行}',
                 '{c|textAlign: left}紧跟左{e|这两块}{f|在剩余区域居中}{d|textAlign: right}',
                 '{g|textVerticalAlign: top}{h|最大文字}{i|textVerticalAlign: bottom}'
             ].join('\n'),
             textFill: 'red',
             font: '18px Arial',
             rich: {
                 b: {
                     textShadowBlur: 3,
                     textShadowColor: '#555',
                     textShadowOffsetX: 2,
                     textShadowOffsetY: 2
                 },
                 c: {
                     font: '30px Microsoft YaHei',
                     textFill: 'green'
                 },
                 d: {
                     font: '22px Arial',
                     textFill: '#871299',
                     textAlign: 'right'
                 },
                 e: {
                     font: '22px Arial',
                     textFill: '#367199',
                     textAlign: 'center'
                 },
                 f: {
                     font: '12px Arial',
                     textFill: '#941122',
                     textAlign: 'center'
                 },
                 g: {
                     font: '12px Arial',
                     textVerticalAlign: 'top'
                 },
                 h: {
                     font: '34px Arial'
                 },
                 i: {
                     font: '18px Arial',
                     textVerticalAlign: 'bottom'
                 },
                 j: {
                     font: '23px Arial',
                     textFill: '#922889',
                     textVerticalAlign: 'top',
                     lineHeight: 100
                 },
                 k: {
                     font: '14px Arial',
                     textFill: '#126354',
                     textVerticalAlign: 'bottom',
                 },
                 l: {
                     font: '18px Arial',
                     textFill: '#331199',
                     textBorderColor: '#11aa11',
                     textBorderWidth: 2,
                     textBorderRadius: 4,
                     textBackgroundColor: 'rgba(0,0,0,0.1)',
                     textPadding: [10, 20]
                 },
                 m: {
                     font: '9px Arial',
                     textFill: '#aabbcc',
                     textBackgroundColor: '#224433',
                     textBorderRadius: 8,
                     textPadding: [10, 20, 30, 40],
                     textVerticalAlign: 'top'
                 },
                 n: {
                     textAlign: 'right',
                     textVerticalAlign: 'bottom',
                     textBackgroundColor: '#6712ab',
                     width: 100
                 },
                 o: {
                     textAlign: 'center',
                     width: 100,
                     textBackgroundColor: '#99aa44'
                 }
             }
         },
         draggable: true
     }));
 </script>
</body>
</html>

**Comment by caoxiaoxiaoming** [comment]
var zr = zrender.init(document.getElementById('main'), null, {
	renderer: "svg"
});

**Comment by Ovilia** [comment]
rich 暂时没法支持 SVG，参见：https://echarts.baidu.com/tutorial.html#%E4%BD%BF%E7%94%A8%20Canvas%20%E6%88%96%E8%80%85%20SVG%20%E6%B8%B2%E6%9F%93
