### ISSUE TITLE
Firefox下面 image shape无法显示?

### ISSUE THREAD

**Issue by fenix666** [ecomfe/zrender#45]
Firefox下面image无法显示，就拿Demo截图如下：

IE 10:
![ie10](https://f.cloud.github.com/assets/5909793/1513161/e7351f6c-4adc-11e3-90c6-6f57b5bb9856.png)

Chrome Version: 30.0:
![chrome v30 0](https://f.cloud.github.com/assets/5909793/1513169/ff7ada26-4adc-11e3-82d2-e24fa078d5c6.png)

Firefox Version: 25 无法显示
![ff v25](https://f.cloud.github.com/assets/5909793/1513174/147b2d04-4add-11e3-8d8c-83110f6ab57e.png)

**Comment by freedyc** [comment]
Image包含svg图片无法展示
