### ISSUE TITLE
现在的demo，感觉还没有以前的demo好

### ISSUE THREAD

**Issue by tkggusraqk** [ecomfe/zrender#491]
以前的示例网站在哪里找？

**Comment by Ovilia** [comment]
以前是什么时候以前？zrender 的 demo 上线后基本没改过，你指的是 zrender 的 demo 吗？

**Comment by tkggusraqk** [comment]
@Ovilia 我大概3年前用过，那个时候有切水果的demo,好多呢，可以在线调试代码。

**Comment by Ovilia** [comment]
你说的是 http://gallery.echartsjs.com 吗？这个是 ECharts 的作品社区

**Comment by tkggusraqk** [comment]
@Ovilia 不是这个，应该是15年的时候，我还用zrender搞过几个h5的小游戏，当时的官网还是https://ss0.baidu.com/73x1bjeh1BF3odCf/it/u=1139851387,3422180174&fm=85&s=18FAC8121D1354C01840E148030030F3 这个图片

**Comment by Hchenxiao** [comment]
http://kener.github.io/zrender/index.html  是这个？

**Comment by Ovilia** [comment]
@tkggusraqk 为什么觉得那时候的好用呢？具体是什么功能？

**Comment by llcat** [comment]
我也觉得现在zrender的文档例子相对少了点, 要能像echarts那样在线try it就挺好的, 不过直接用zrender的人可能相对少些, 靠社区的力量做成gallery估计有难度~期待你们的next版本
