### ISSUE TITLE
怎么使用attr修改贝塞尔曲线的位置

### ISSUE THREAD

**Issue by zhouhuan0910** [ecomfe/zrender#510]
代码ji及效果如下
![image](https://user-images.githubusercontent.com/22877154/66469878-4b065180-eabb-11e9-9852-850e5e6d57a0.png)
![image](https://user-images.githubusercontent.com/22877154/66469908-5194c900-eabb-11e9-9896-ae2a020a9b4c.png)

现在是我想要动态根据鼠标的位置来改变贝塞尔曲线的位置，使用attr应该如何修改？
目前是使用animateTo可以做到，但是有一定的延时，想要使用attr实时改变曲线的位置。
尝试attr('shape', { y: 50 })，但是不生效

**Comment by Ovilia** [comment]
不是 `y`，是 `y1`、`y2`？

**Comment by zhouhuan0910** [comment]
![image](https://user-images.githubusercontent.com/22877154/66566929-ba9e3e80-eb98-11e9-9fda-8dbbeb3831a4.png)
to通过这种方式解决
