### ISSUE TITLE
new zrender.Polygon()传入rotation不起作用

### ISSUE THREAD

**Issue by andy259** [ecomfe/zrender#518]
new zrender.Polygon({
            style:{
                lineWidth:2,
                stroke:'rgb(0,255,0)',
            },
            shape:{
                points:points,
            },
            rotation:90/180*Math.PI
});

传入rotation，图形绘制不出来。
如果希望进行旋转，那么正确的做法是什么了？

**Comment by Heisenbilin** [comment]
创建之后用polygon实例.attr再设置一下，可以设置一下origin指定旋转中心

**Comment by andy259** [comment]
谢Heisenbilin，可以旋转了。

 polygon实例.attr('origin',[x,y]);//指定旋转中心
polygon实例.attr('rotation',90/180*Math.PI);//旋转90度

**Comment by andy259** [comment]
谢Heisenbilin，可以旋转了。

 polygon实例.attr('origin',[x,y]);//指定旋转中心
polygon实例.attr('rotation',90/180*Math.PI);//旋转90度

**Comment by andy259** [comment]
谢Heisenbilin，可以旋转了。

 polygon实例.attr('origin',[x,y]);//指定旋转中心
polygon实例.attr('rotation',90/180*Math.PI);//旋转90度
