### ISSUE TITLE
大神，能否给提供一个 opts.style.rich 使用的例子，不会使用这个东西

### ISSUE THREAD

**Issue by joinhappy81** [ecomfe/zrender#523]

**Comment by Ovilia** [comment]
https://echarts.apache.org/zh/tutorial.html#%E5%AF%8C%E6%96%87%E6%9C%AC%E6%A0%87%E7%AD%BE 这里的例子，点击「编辑示例」可以看到源码。

**Comment by buck2015** [comment]
Sector
只有opts.style.text
rich知道怎么写，但是，formatter要怎么写呢？
是否支持，字符串模板？
 模板变量有：
{a}：系列名。
{b}：数据名。
{c}：数据值。
{@xxx}：数据中名为'xxx'的维度的值，如{@product}表示名为'product'` 的维度的值。
{@[n]}：数据中维度n的值，如{@[3]}` 表示维度 3 的值，从 0 开始计数。

我的需求是，画一个Sector，然后在中间写一百分比数值，和一个数值说明，这两都是动态的。

**Comment by buck2015** [comment]
知道了，formatter内容直接写到text里
