### ISSUE TITLE
zrender.Path.extend 扩展图形, 鼠标mouseout事件问题

### ISSUE THREAD

**Issue by isensen** [ecomfe/zrender#537]
利用zrender.Path.extend扩展了个新图形,  这个新图形需求要有一个斜线指向解释性文字. 写buildPath时,发现第一个参数只能构建路径,不能绘制文字, 输出对象,发现有ctx._ctx可以取到原生context, 所以利用ctx._ctx绘制了文字.   第二步要实现鼠标经过图形时和离开图形时的变化, 经过图形,mouseover事件,修改了一下style.stroke 颜色 , 鼠标事件mouseout离开时, 修改回原来的颜色. 发现鼠标进入时没有问题, 但鼠标离开时文字消失了, 应该是ctx._ctx 为undefined了,请问这个怎么方便的解决, 是BUG吗?

追加:
貌似不是因为ctx._ctx的问题, 打了一下断点, mouseout的时候, 没有走buildPath?

**Comment by 1011875777** [comment]
你好，因为我要画拥有不同的颜色的不规则图形，回调中的path提供的方法太少，所以我用了path._ctx 来绘制，但是发现问题， 在绘制显示后，使用add添加其它图形时，之前用path._ctx绘制的图形都消失了，你有没有遇到过这样的情况？
