### ISSUE TITLE
zrender.Path.extend 扩展新的图形，在图形上添加了点击事件，为什么无法点击

### ISSUE THREAD

**Issue by Evenssi** [ecomfe/zrender#538]
zrender.Path.extend  我扩展过绘制自定义的横线和竖线，添加了点击事件，当鼠标处在曲线上的时候，点击曲线可以更改曲线的颜色和粗细，均可以实现。但是今天按照同样的方法扩展绘制了空心圆，却怎么点击都无法进入点击事件，本来我写的是当鼠标在该对象上的时候样式变为十字，也没有实现，想知道为什么？？怎么解决

**Comment by evaydh** [comment]
空心圆内部没有颜色填充，就没有实体，就跟不存在东西一样。填充个颜色或者透明色试试？

Path.extend的使用方法官方给的例子和说明实在太少了，打印buildPath(path,shape)里的path会看到有很多扩展用法。然而用起来是和canvas有点不同。我就是因位不会canvas才想用zrender绕过去的啊。。

**Comment by Evenssi** [comment]
这个问题已经解决了：因为在扩展的方法里面我是使用的canvas对象的，就是使用了ctx.acr()，虽然可以绘制出来，但是该扩展图形无法使用鼠标获取到，无法相应点击事件。也就是我在此提的问题。后来我在看了官方文档加上调试之后，发现buildPath里面是有很多的绘制方法的，后改用的path.arc()绘制圆形，就可以响应点击事件了。

**Comment by evaydh** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Evenssi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月29日(星期六) 晚上7:44
收件人:&nbsp;"ecomfe/zrender"<zrender@noreply.github.com&gt;;
抄送:&nbsp;"萌萌的猫神"<565272712@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ecomfe/zrender] zrender.Path.extend 扩展新的图形，在图形上添加了点击事件，为什么无法点击 (#538)




这个问题已经解决了：因为在扩展的方法里面我是使用的canvas对象的，就是使用了ctx.acr()，虽然可以绘制出来，但是该扩展图形无法使用鼠标获取到，无法相应点击事件。也就是我在此提的问题。后来我在看了官方文档加上调试之后，发现buildPath里面是有很多的绘制方法的，后改用的path.arc()绘制圆形，就可以响应点击事件了。

**Comment by Evenssi** [comment]
> 空心圆内部没有颜色填充，就没有实体，就跟不存在东西一样。填充个颜色或者透明色试试？
> 
> Path.extend的使用方法官方给的例子和说明实在太少了，打印buildPath(path,shape)里的path会看到有很多扩展用法。然而用起来是和canvas有点不同。我就是因位不会canvas才想用zrender绕过去的啊。。

谢谢。这个问题已经解决了：因为在扩展的方法里面我是使用的canvas对象，就是使用了ctx.acr()，虽然可以绘制出来，但是该扩展图形无法使用鼠标获取到，无法相应点击事件。也就是我在此提的问题。后来我在看了官方文档加上调试之后，发现buildPath里面是有很多的绘制方法的，后改用的path.arc()绘制圆形，就可以响应点击事件了。后面有时间我会试一下你说的在圆中填充颜色试一试看可不可行。^-^
