### ISSUE TITLE
求问关于position 和 shape里的x,y之间的区别？

### ISSUE THREAD

**Issue by evaydh** [ecomfe/zrender#574]
给定一个矩形框(new zrender.Rect())

如果设置其draggable属性为true时，其实可以拖动的，查看拖动前后的属性发现是通过设置position属性实现的。

但如果通过设置shape属性下的x和y的值也可以实现同样的效果。

请问下，这position 与 shape下的x和y 之间有什么样的差别？

**Comment by Ovilia** [comment]
position 是图形的位置，x y 是矩形左上角的坐标，只是画一个矩形的话，从效果上看的确是一样的。但是对于坐标变换的情况下，可能因为锚点不同而不同。一般情况下，建议使用 position 设置位置。

**Comment by phenomLi** [comment]
x, y是相对于position的，换句话说也就是图形自身的坐标原点。

例如你设置了position: [100, 100]，然后再设置x = 10，y = 10，那么图形在canvas的实际的位置是[110, 110]

**Comment by evaydh** [comment]
感谢上面两位，明白了。

多尝试一些之后，zrender中管理画布上的图形元素，比如实现多个图形交互联动的时候，还是使用position更加方便一些。
