### ISSUE TITLE
zrender.Image图像实例如何应用描边或高亮效果？

### ISSUE THREAD

**Issue by yangmiao7** [ecomfe/zrender#579]
业务场景：图像在项目中实现了类似地图坐标点的效果（不随地图缩放而缩放），点击时想要对被点击的zrender.Image图像实例进行突出展示（高亮处理，或增加描边等）

Displayable类中大部分通用的style样式对图像实例没有效果，请问有什么方法可以实现呢？

**Comment by yuxiaoyin** [comment]
高亮好像不得行，你解决了么 ？
