### ISSUE TITLE
在 next 版本发布之前，是否有官方的 d.ts 文件？

### ISSUE THREAD

**Issue by beetaa** [ecomfe/zrender#599]
刚刚得知 zrender 有一个 ts 重构的 next 版本，但目前还没有发布到 npm 上。现在的 d.ts 文件有一个 `@types/zrender`，但基本不能用。不知道 next 版本的发布计划如何？在此之前能否提供一个目前版本的官方 d.ts 文件？谢谢你们的辛劳工作。以下是目前的 `@types/zrender` 定义文件，太简单，而且报错：

```ts
declare namespace zrender {
    type X = number;
    type Y = number;
    type X2 = number;
    type Y2 = number;
    type GlobalCoords = boolean;
    type ColorStops = Array<{
        offset: number;
        color: string;
    }>;

    /**
     * x, y, x2, y2 are all percent from 0 to 1
     */
    interface LinearGradient {
        new (
            /** @default 0 */
            x?: X,

            /** @default 0 */
            y?: Y,

            /** @default 1 */
            x2?: X2,

            /** @default 0 */
            y2?: Y2,

            /** @default [] */
            colorStops?: ColorStops,

            /** @default false */
            globalCoord?: GlobalCoords,
        ): {
            type: 'linear';
            x: X;
            y: Y;
            x2: X2;
            y2: Y2;
            colorStops: ColorStops;
            globalCoord: GlobalCoords;

            addColorStop(offset: number, color: string): void;
        };
    }
}

declare module 'zrender' {
    export = zrender;
}
```

**Comment by beetaa** [comment]
报错信息

![image](https://user-images.githubusercontent.com/5688224/81250084-af3dc380-9052-11ea-9bff-dda1d3d6580f.png)

**Comment by Ovilia** [comment]
只有 ECharts 的 https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/echarts
能否用 next 分支呢？

**Comment by beetaa** [comment]
@Ovilia 我尝试过 next 分支，但在我的 vue3.0 + webpack 配置中，出现大量类型信息报错，这些信息主要来自 vscode 插件 vetur，目前我还不知道是分支的问题还是我的配置问题，所以才有此问。另外，next 分支好像是基于 4.2 开发的。其实定义文件就是代码提示方便点，长远来看，你们确实也不要花时间在 es6 版的定义文件上，期待你们专心完善 next 分支。zrender 非常棒！加油！

**Comment by beetaa** [comment]
@Ovilia 我尝试过 next 分支，但在我的 vue3.0 + webpack 配置中，出现大量类型信息报错，这些信息主要来自 vscode 插件 vetur，目前我还不知道是分支的问题还是我的配置问题，所以才有此问。另外，next 分支好像是基于 4.2 开发的。其实定义文件就是代码提示方便点，长远来看，你们确实也不要花时间在 es6 版的定义文件上，期待你们专心完善 next 分支。zrender 非常棒！加油！
