### ISSUE TITLE
Path.extend中如何设置颜色？

### ISSUE THREAD

**Issue by 1011875777** [ecomfe/zrender#602]
我正在使用Path.extend来绘制一个坐标系，let Axis = zrender.Path.extend({...}）， 我想要x轴和y轴使用不同颜色，但是我发现只能在new Axis的时候设置style.stroke, 这样整个坐标系都是同一颜色；

想请教一下zrender有没有办法像canvas那样控制一个图形中的每条line的宽度和颜色；

**Comment by Ovilia** [comment]
每条线不同颜色的话，应该画成不同的线

**Comment by 1011875777** [comment]
谢谢你的回答，你的意思是用多个zrender.Line来构建坐标系吗？ 我目前的做法是在zrender.Path.extend.buildPath 里面使用path.moveTo和path.lineTo一次性画好坐标系，但是不能设置不同的颜色，后面我尝试使用了path._ctx 来绘制

**Comment by llcat** [comment]
@100pah 我觉得xAxis和yAxis是不同的图元, 你应该分开绘制会比较好, echarts里面有实现好的笛卡尔坐标系可以参考下。[CartesianAxis](https://github.com/apache/incubator-echarts/blob/master/src/component/axis/CartesianAxisView.js), [AxisBuilder](https://github.com/apache/incubator-echarts/blob/master/src/component/axis/AxisBuilder.js)

**Comment by 1011875777** [comment]
好的谢谢 @llcat
