### ISSUE TITLE
draw shape is Asynchronous？

### ISSUE THREAD

**Issue by deyihu** [ecomfe/zrender#608]
```js

zr.add(text);
// not find draw info
console.log(canvas.toDataURL())

setTimeout(()=>{
  console.log(canvas.toDataURL())
},200)

```

If the drawing of pictures is asynchronous, it can be understood that the drawing of some vector graphics should not be asynchronous

[example](https://codepen.io/deyihu/pen/LYGWmEM?editors=1010)

**Comment by llcat** [comment]
@deyihu 绘制图元是异步的, zrender内部是用的`requestAnimationFrame`每16ms绘制一次图元, 用了一个标记位记录是否绘制完了所有图元, 绘制完成后会发送一个`rendered`事件。你可以参考下`Painer.js`中的[`_paintList`](https://github.com/ecomfe/zrender/blob/c55198452a21267be59e7371a318ba3c967a3f7a/src/Painter.js#L378)和[`_doPaintList`](https://github.com/ecomfe/zrender/blob/c55198452a21267be59e7371a318ba3c967a3f7a/src/Painter.js#L414)方法。
如果你是想在绘制完成后导出图片, 建议监听`rendered`事件:
```javascript
zr.on('rendered', ()=>{
  console.log('rendered')
  console.log(canvas.toDataURL())
})
```

**Comment by deyihu** [comment]
@llcat  thanks
