### ISSUE TITLE
Fill pattern image do not show in Chrome browser, but is ok in Firefox & Safari browser.

### ISSUE THREAD

**Issue by mihayinoviki** [ecomfe/zrender#615]
I found that when I fill a shape with pattern image, the image do not show in Chrome browser. But it's ok in Firefox & Safari browser.

code : 
```javascript
        let img = new Image();
        img.src= './p.png';
        img.onload = () =>{
            var circle = new zrender.Circle({
                shape: {
                    cx: 100,
                    cy: 100,
                    r:80
                },
                style: {
                    fill: {
                        image: img
                    },
                    stroke: '#00FF00',
                },
            });
            zr.add(circle)
        };
```

view in Chrome:
![2020-07-15_11-24-13](https://user-images.githubusercontent.com/477539/87499885-d38ad180-c68d-11ea-9504-8e0b1450dc84.jpg)

view in Firefox:
![2020-07-15_11-26-12](https://user-images.githubusercontent.com/477539/87499963-0634ca00-c68e-11ea-947c-2f2415a1e306.jpg)

**Comment by mihayinoviki** [comment]
anybody see that!

**Comment by llcat** [comment]
chrome version and zrender version? i try in chrome is ok

**Comment by mihayinoviki** [comment]
Finally Ok, may be someone  extension in my Chrome make this problem, after reinstall same version Chrome everything ok.  thanks for @llcat
