### ISSUE TITLE
[Typescript]:v5.0.1 Cannot resolve dependency '../graphic/text/parse' at 'node_modules/zrender/src/graphic/text/parse'

### ISSUE THREAD

**Issue by jimizai** [ecomfe/zrender#677]
- zrender: v5.0.1
- typescript: v4.1.2
- node: v14.8.0
- os: Mac
引入方式尝试了 import * as zrender from 'zrender' import zrender from 'zrender' 都是不得行

**Comment by bdwenxi** [comment]
weback配置里resolve.alias加上这条配置: 'zrender': utils.pathResolve('./node_modules/zrender/dist/zrender.min.js')
你直接指向package.json里的main(index.js)的话会找不到graphical/text/parse这个module的 @jimizai

**Comment by jimizai** [comment]
所以是怎么解决的， 我按照你的操作报错找不到'../graphic/text/parse' ，还有utils.pathResolve指的是node内置模块path.resolve吗，代码如下：
```javascript
config.resolve.alias.zrender = path.resolve(
   __dirname,
  './node_modules/zrender/dist/zrender.min.js'
);
```

**Comment by bdwenxi** [comment]
@jimizai `utils.pathResolve`是我封装的一个工具类(其实就是你的path.resolve),  把webpack config里alias指向
```
node_modules/zrender/dist/zrender.min.js
```
即可

还有确认一个问题: 你的webpack版本是5吗?
