### ISSUE TITLE
是否可把像LineProps、PathStyleProps等Type给expose出来, 方便基于Ts的二次封装

### ISSUE THREAD

**Issue by bdwenxi** [ecomfe/zrender#682]
是否可把像LineProps、PathStyleProps等Type给expose出来, 方便基于Ts的二次封装?

**Comment by lzxb** [comment]
如果确定可以的话，我可以贡献一下这方面的。

**Comment by pissang** [comment]
@lzxb 可以，非常感谢

**Comment by Yang2007** [comment]
我也基于zRender进行了二次开发，你可以自己手动写，类似于这样：
shape?: Partial<typeof Rect.prototype.shape>;
style?: Partial<typeof Image.prototype.style>;

**Comment by lzxb** [comment]
不好意思，最近两周工作比较忙。今天才抽时间处理一下。可以看看有哪些类型是缺少的。

**Comment by lzxb** [comment]
有计划什么时候发布一个版本吗？

**Comment by pissang** [comment]
@lzxb 下个月初会发布一个新版本
