### ISSUE TITLE
5.0.3版本graphic.js中引入'../graphic/text/parse'不存在

### ISSUE THREAD

**Issue by alisonysy** [ecomfe/zrender#703]
npm install zrender安装的，vue的2.6.x版本，没有ts
引入时报错，the relative module was not found
打开zrender的src/vml/graphic.js，有一行
`import * as textContain from '../graphic/text/parse';`

但graphic目录下并没有text目录

**Comment by bdwenxi** [comment]
webpack resolve.alias下面配置一条: `'zrender': path.resolve('./node_modules/zrender/dist/zrender.min.js')`. 
你import ‘zrender’的话node会优先查找es module的入口文件而不是package.json中的main: dist/zrender.js.
 所以建议你按照上述配置先hack下, 等待官方的修复吧 @alisonysy

**Comment by wmlgl** [comment]
import * as zrender from "zrender/esm/zrender";
import { Circle } from "zrender/esm/export";
import CanvasPainter from "zrender/esm/canvas/Painter";

zrender.registerPainter('canvas', CanvasPainter);

这样可以
