### ISSUE TITLE
5.0 文档什么时候更新？

### ISSUE THREAD

**Issue by LKen** [ecomfe/zrender#729]
感觉5.0挺多api变动的呀，每次绘制不出图形，都要看看源码和issue，请问有新的文档地址吗？感谢！！

**Comment by aixi134** [comment]
同求+1

**Comment by yokattasama** [comment]
文档太不详细了，好多基础的概念，配置都不明白，好不容易找了个demo，运行了还报很多警告，说什么某某配置项已被替换为***

**Comment by MichaelShen** [comment]
是啊，文档写的太不清晰了，demo 和代码示例都没有

**Comment by HawthornXU** [comment]
we need new doc! /手动滑稽

**Comment by wanging1460** [comment]
求文档啊，文档严重影响了开发效率。哭脸

**Comment by RockyF** [comment]
新版的使用略有出入，尤其是用ts开发项目接入zrender，快要窒息了！ 😭

**Comment by shaojingchao** [comment]
什么时候能把文档对应的版本号加上？

**Comment by JacquesYW** [comment]
23年了,  5.0的文档依然没有  /手动滑稽

**Comment by Ovilia** [comment]
文档有问题的欢迎提 PR
