### ISSUE TITLE
请问在zrender.Line中设置z:-1 为啥线还是在其他元素上面。

### ISSUE THREAD

**Issue by shawnXHC** [ecomfe/zrender#731]

**Comment by shawnXHC** [comment]
这些元素都是被添加到一个group中的

**Comment by pissang** [comment]
提供一下例子？

**Comment by shawnXHC** [comment]
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Bezier Animation</title>
    <script src="../dist/zrender.js"></script>
</head>

<body>
    <div id="main" style="width:1000px;height:600px;"></div>
    <script type="text/javascript">
        var zr = zrender.init(document.getElementById('main'));
        var group = new zrender.Group()
        var line = new zrender.Line({
            shape: {
                x1: 70,
                y1: 0,
                x2: 70,
                y2: 600,
            },
            z: -1
        });

        var image = new zrender.Image({
            style: {
                image: 'asset//hahah.svg',
                x: 50,
                y: 50,
            }
        })

        group.add(line)
        group.add(image)
        zr.add(group);
    </script>
</body>

</html>

**Comment by shawnXHC** [comment]
`<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Bezier Animation</title>
    <script src="../dist/zrender.js"></script>
</head>

<body>
    <div id="main" style="width:1000px;height:600px;"></div>
    <script type="text/javascript">
        var zr = zrender.init(document.getElementById('main'));
        var group = new zrender.Group()
        var line = new zrender.Line({
            shape: {
                x1: 70,
                y1: 0,
                x2: 70,
                y2: 600,
            },
            z: -1
        });

        var image = new zrender.Image({
            style: {
                image: 'asset//hahah.svg',
                x: 50,
                y: 50,
            }
        })

        group.add(line)
        group.add(image)
        zr.add(group);
    </script>
</body>

</html>`

**Comment by shawnXHC** [comment]
var zr = zrender.init(document.getElementById('main'));
        var group = new zrender.Group()
        var line = new zrender.Line({
            shape: {
                x1: 70,
                y1: 0,
                x2: 70,
                y2: 600,
            },
            z: -1
        });

        var image = new zrender.Image({
            style: {
                image: 'asset//hahah.svg',
                x: 50,
                y: 50,
            }
        })

        group.add(line)
        group.add(image)
        zr.add(group);

`

**Comment by beetaa** [comment]
@shawnXHC 应该是视觉错觉，我这边的运行结果没问题。

```js
const zr = zrender.init(document.getElementById("ok"))

var group = new zrender.Group()
var line = new zrender.Line({
    shape: {
        x1: 70,
        y1: 0,
        x2: 70,
        y2: 600,
    },
    z: -1
});

var image = new zrender.Image({
    style: {
        image: 'https://iconfont.alicdn.com/t/3c0f2c09-452c-49cd-852d-8f0a66873abe.png',
        x: 0,
        y: 50,
    }
})

group.add(line)
group.add(image)
zr.add(group)
```

![image](https://user-images.githubusercontent.com/5688224/120196576-9520e580-c252-11eb-8e56-75b638cb61cd.png)

**Comment by shawnXHC** [comment]
svg就不行。

**Comment by shawnXHC** [comment]
> @shawnXHC 应该是视觉错觉，我这边的运行结果没问题。
> 
> 
> 
> ```js
> 
> const zr = zrender.init(document.getElementById("ok"))
> 
> 
> 
> var group = new zrender.Group()
> 
> var line = new zrender.Line({
> 
>     shape: {
> 
>         x1: 70,
> 
>         y1: 0,
> 
>         x2: 70,
> 
>         y2: 600,
> 
>     },
> 
>     z: -1
> 
> });
> 
> 
> 
> var image = new zrender.Image({
> 
>     style: {
> 
>         image: 'https://iconfont.alicdn.com/t/3c0f2c09-452c-49cd-852d-8f0a66873abe.png',
> 
>         x: 0,
> 
>         y: 50,
> 
>     }
> 
> })
> 
> 
> 
> group.add(line)
> 
> group.add(image)
> 
> zr.add(group)
> 
> ```
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5688224/120196576-9520e580-c252-11eb-8e56-75b638cb61cd.png)
> 
> 

您试下用SVG图片

**Comment by pissang** [comment]
@shawnXHC 是因为这个 svg 图片底下是透明的吧
