### ISSUE TITLE
5.1.1绘制元素时，添加text没用

### ISSUE THREAD

**Issue by liubinyu19891127** [ecomfe/zrender#776]
**代码示例：**
使用的cdn：https://cdn.bootcdn.net/ajax/libs/zrender/5.1.1/zrender.min.js
<div id="container"></div>
js部分：

var zr = zrender.init(document.getElementById('container'));

var Circle = new zrender.Circle({
  shape: {
    cx: 100,
    cy: 100,
    r: 20,
  },
  style: {
    text: 'aaa',
    textFill: '#ff5500',
  }
});
zr.add(Circle);
**问题：**
页面只显示了一个黑色圆圈，没有aaa文字

**Comment by pissang** [comment]
```ts
var Circle = new zrender.Circle({
shape: {
cx: 100,
cy: 100,
r: 20,
},
textContent: new zrender.Text({
  style: { text: 'aaa', fill: '#ff5500' }
})
});
```

**Comment by liubinyu19891127** [comment]
文档里没有找到，是不是5.0的文档还没有更新出来，没有textContent属性

**Comment by pissang** [comment]
@liubinyu19891127 嗯 5.0 的文档还没有更新，抱歉

**Comment by wxg-dagege** [comment]
我吐了，文档没更新版本就不要更新呀，哭了呀，搞了一上午，都快崩溃了

**Comment by wxg-dagege** [comment]
而且就算更新了代码我用以前的写法是不是应该给个警告或者抛个错误，提个小小的介意哈

**Comment by pissang** [comment]
@wxg-dagege 嗯抱歉，因为 5.0 目前功能主要是为了满足 echarts 的需求，迭代比较快，文档也没来得及更上。如果碰到很多问题的话可以先固定在 4.x 的版本

**Comment by guozhaoxi** [comment]
现在是2021年11月19日，我说怎么文字就是不显示，我翻源码，也没找到text,我还以为被抛弃了呢，看到这个issue，我泪目了。
希望老板有时间的话 还是更一下文档吧

**Comment by soom-lupulus** [comment]
2022年6月了，5版本的文档还没有吗？

**Comment by somnusnrlq** [comment]
是啊 最起码提示下！！搞了半天原来是新版的不兼容了！

**Comment by wang1212** [comment]
大版本更新，不兼容不是很正常的事情么，作为开发者，这么大惊小怪的？

**Comment by ListenToMee** [comment]
2024年5月了，新文档还没有么？
