### ISSUE TITLE
Typescript 编译报类型错误

### ISSUE THREAD

**Issue by lzxb** [ecomfe/zrender#777]
![image](https://user-images.githubusercontent.com/8424643/123027490-7f957a80-d410-11eb-8a94-24bf829dc94e.png)

index.d.ts 应该使用
```typescript
export * from './lib/zrender';
export * from './lib/export';
```

**Comment by JonathonChen** [comment]
latest version 5.3.0 also has this problem @lzxb @pissang

**Comment by lzxb** [comment]
A new version needs to be released
