### ISSUE TITLE
zrender-lib-core-util.js-trim方法参数应为字符串，应该判断参数是否为字符串，不应直接调用replace方法

### ISSUE THREAD

**Issue by fansUI** [ecomfe/zrender#782]
![image](https://user-images.githubusercontent.com/50223100/124530516-3a753d80-de3f-11eb-948e-6cdf3f6a25f1.png)

**Comment by fansUI** [comment]
![image](https://user-images.githubusercontent.com/50223100/124531205-a2785380-de40-11eb-8c5a-baeac10a2d78.png)

**Comment by xfz1314** [comment]
解决了吗？我也遇到了一样的问题

**Comment by fansUI** [comment]
.
