### ISSUE TITLE
请问如何用ECHARTS 5版本调用zrender，实现调用 VML 渲染器， 使ECHARTS 5支持IE8 

### ISSUE THREAD

**Issue by lhj117383609** [ecomfe/zrender#785]
请问如何用ECHARTS 5版本调用zrender，实现调用 VML 渲染器， 使ECHARTS 5支持IE8 

ECHARTS 5官方升级指南
（浏览器兼容性
v5 不再支持 IE8 浏览器。我们不再继续维护和升级之前的 VML 渲染器 来着实现 IE8 的兼容。如果使用者确实有很强的需求，那么欢迎提 pull request 来升级 VML 渲染器，或者单独维护一个第三方 VML 渲染器，我们从 v5.0.1 开始支持注册独立的渲染器了。）

麻烦具体代码如何调用，谢谢

**Comment by plainheart** [comment]
```ts
import { registerPainter } from 'zrender/lib/zrender';
import VMLPainter from 'zrender/lib/vml/Painter';
registerPainter('vml', VMLPainter);
```
