### ISSUE TITLE
如何让图片上面的文字， 跟着图片一起按照中心点旋转，而不是横向移动？

### ISSUE THREAD

**Issue by sssKKwater** [ecomfe/zrender#797]
this.getPaiZi('活动', this.zrW / 2, 220)
    //创建一个标题牌子（文字，横纵坐标）
    getPaiZi(text, x, y) {
      let paiZi = new zrender.Image({
        style: {
          position: [0, 0],
          image: shuPaiZi,
          width: 52,
          height: 40,
          y: y,
          x: x
        },
        textContent: new zrender.Text({
          style: {
            text: text,
            fontWeight: '800',
            fontSize: '14',
            textFill: '#333333',
            **textPosition: 'bottom',
            transformText: true,**  //这个代码并没有用
            x: (52 - 28) / 2,
            y: 20
          }
        }),
        textConfig: {
          position: 'center',
          origin: [x + 28, y]
        }
      }).on('click', () => {
        paiZi.animate('')
          .when(100, {
            origin: [x + 28, y],
            rotation: 0
          })
          .when(1000, {
            origin: [x + 28, y],
            rotation: -0.3
          })
          .when(2000, {
            origin: [x + 28, y],
            rotation: 0.3
          })
          .when(3000, {
            origin: [x + 28, y],
            rotation: 0
          }).start()
      })
      this.zr.add(paiZi)
    }
![image](https://user-images.githubusercontent.com/19711786/129523006-b22dc733-22ea-4ee8-b721-e7a27528136e.png)

按理说图片上面的文字，应该是跟图片一样的倾斜角的，现在并没有发生对应的旋转而是对应角度平移

**Comment by sssKKwater** [comment]
一人血书，求更新文档 QAQ

**Comment by plainheart** [comment]
动画的时候可以给 `text` 也加上 `rotation`。

```js
paiZi.animate('')
  .when(100, {
      rotation: 0
  })
  .when(1000, {
      rotation: -0.3
  })
  .when(2000, {
      rotation: 0.3
  })
  .when(3000, {
      rotation: 0
  })
  .during(el => {
      el.getTextContent().rotation = el.rotation;
  })
  .start()
  ```

**Comment by sssKKwater** [comment]
> 动画的时候可以给 `text` 也加上 `rotation`。
> 
> ```js
> paiZi.animate('')
>   .when(100, {
>       rotation: 0
>   })
>   .when(1000, {
>       rotation: -0.3
>   })
>   .when(2000, {
>       rotation: 0.3
>   })
>   .when(3000, {
>       rotation: 0
>   })
>   .during(el => {
>       el.getTextContent().rotation = el.rotation;
>   })
>   .start()
> ```
![image](https://user-images.githubusercontent.com/19711786/129529256-fb8cedb6-92c9-4e1a-8591-5c66e0554777.png)
![image](https://user-images.githubusercontent.com/19711786/129529424-e1f36ab6-e9a2-4af6-b332-4cf91c93cf56.png)

不行啊。。。这个文字的位移更奇怪了哈哈

**Comment by plainheart** [comment]
思路大概是这样，可能你还需要调整下 origin。

**Comment by plainheart** [comment]
写了个小demo，你可以参考下。https://codepen.io/plainheart/pen/mdmggWj

**Comment by sssKKwater** [comment]
> 写了个小demo，你可以参考下。https://codepen.io/plainheart/pen/mdmggWj
thankU，找到问题所在了
        textConfig: {
          position: 'insideBottom'  //使用了insideBottom而不是inside，所以他没跟着跑
        },

**Comment by sssKKwater** [comment]
> 写了个小demo，你可以参考下。https://codepen.io/plainheart/pen/mdmggWj

多谢多谢，您真厉害，麻烦问一下有没有相关的群？想学习一下QwQ

**Comment by plainheart** [comment]
我这暂时没有 😄 可以多看看源码。B站上有一个由 ECharts 核心开发者分享的：”深入浅出ECharts源码“ 视频，https://www.bilibili.com/video/BV1TJ411s7pj，建议看下。也欢迎后面给 ECharts 提 PR 修修 bug，加个 feature，当然要是感觉难度太大帮助完善下文档也是很欢迎的哈~
