### ISSUE TITLE
can i use decal in zrender? (v.5.1.1)

### ISSUE THREAD

**Issue by thdeotjq12** [ecomfe/zrender#800]
I saw decal applied in echart. Is it possible to use decal in zrender as well?
i try this but not working.

```
        const decals = [{
            color: "rgba(0, 0, 255, 0.3)",
            dashArrayX: [1, 0],
            dashArrayY: [2, 5],
            symbolSize: 1,
            rotation: Math.PI / 6,
        }];
        let rect : zrender.Element;
        rect = new zrender.Rect({
            shape:{
                x: this.rect.x,
                y: this.rect.y,
                width: this.rect.w,
                height: this.rect.h,

            },
            style:{
                fill: "blue",
                decal:  decals,
            }
        });

```

I need an example
thank you!

**Comment by ChenXiaofan** [comment]
zrender supports decal, but u should draw it by yourself like Path.extend, there is no way to draw it directly by zrender

**Comment by wayward-man** [comment]
maybe u can use  API `Path.extend ` to  extend a Shape easily ，and draw decal  with the shape

**Comment by Ovilia** [comment]
@thdeotjq12 You cannot use decal directly in ZRender. The `decal` attribute of `Path` is typed in `PatternObject` which is the pattern generated based on the decal options. If you do wish to implement decal with ZRender, you need to do the similar things as done [in Apache ECharts](https://github.com/apache/echarts/blob/b1ca9f6/src/util/decal.ts#L49).

**Comment by thdeotjq12** [comment]
Thank you for answer. I implemented it by drawing directly.

`
        const pattern1 = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
        const decals = {

            x: this.rect.x,
            y: this.rect.y,
            svgElement : pattern1 ,
            svgWidth: width,
            svgHeight: height,
        };
 style:{
                fill: "blue",
                decal:  decals,
            }
`
