### ISSUE TITLE
new zrender.Image会将canvas上原有绘画内容都清空

### ISSUE THREAD

**Issue by qiaoaimi** [ecomfe/zrender#848]
new zrender.Image会将canvas上原有绘画内容都清空，请问下，这个问题有什么解决办法吗？

**Comment by pissang** [comment]
不会吧，你怎么用的

**Comment by qiaoaimi** [comment]
我们在做一个画图工具，使用的是canvas，可以随便画的那种。需要一个插图功能，并且插入的图片可以随意放大缩小移动等操作，看了zrender这些都是支持的。我简化了一下代码，发您看下，只要调用了zrender，原绘画内容就会消失。
<html lang="zh">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
	<meta http-equiv="Access-Control-Allow-Origin" content="*">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title></title>
 	<script src="./js/jquery.min.js"></script>
	<script type="text/javascript" src="./js/zrender.js"></script>
</head>
<script>
var zr;
var temp = -99999;
var idCount=1;
var group;
window.onload = function() {

}
function image2Base64(img) {
	var canvas = document.createElement("canvas");
	canvas.width = img.width;
	canvas.height = img.height;
	var ctx = canvas.getContext("2d");
	ctx.drawImage(img, 0, 0, img.width, img.height);
	var dataURL = canvas.toDataURL("image/png");
	return dataURL;
}
$(document).ready(function() {
	var canvas = document.getElementById("sketchpad");
	var context = canvas.getContext("2d");
	context.beginPath();//开始绘制线条，若不使用beginPath，则不能绘制多条线条
	context.moveTo(100, 100);//线条开始位置
	context.lineTo(700, 700);//线条经过点
	context.lineTo(100, 700);
	context.lineTo(100, 100);
	context.closePath();//结束绘制线条，不是必须的
   
	context.lineWidth = 5;//设置线条宽度
	context.strokeStyle = "red";//设置线条颜色
	context.stroke();//用于绘制线条

	context.beginPath();
	context.moveTo(200, 100);
	context.lineTo(700, 600);
	context.closePath();
	context.strokeStyle = "black";
	context.stroke();
	zr = zrender.init(canvas);
	group = new zrender.Group();
	var base64="";
	var img = new Image();
	img.setAttribute("crossOrigin",'anonymous')
	img.src="./Images/huihua/huabi.png";
	img.onload=function(){
		base64 = image2Base64(img);
		//alert(base64);
		InsertImage(base64);
	}

});
function InsertImage(base64Data) {
	imgStroke = {
		type: 10, // 默认是1画笔，5是毛笔, 0是橡皮擦，10是图片
		x:200,
		y:0,//this.canvas.height/2,
		imgData:base64Data,
	};
	
	_drawImg(imgStroke);
};
function _drawImg(stroke) {
	if(stroke.type == 10){
	  // 画图片
	  document.body.style.cursor = "wait";
		var img = new Image();
		var oCan = this.context;
		var oCanW = this._width;
		var oCanH = this._height;
		
		img.src = stroke.imgData;
		img.onload = function(){
			var w=img.width;
			var h=img.height;
			if(w>oCanW || h>oCanH) {
				if(w/h > oCanW/oCanH)
				{
					h=h * oCanW / w;
					w = oCanW; 
				}else{
					w=w * oCanH / h;
					h = oCanH;					
				}
			}
			var img1 = new zrender.Image({
				style: {
					image:img.src,
					x: stroke.x-w/2,
					y: stroke.y,
					width: w,
					height:h
				},
				zlevel:temp,
				id:idCount,
				draggable: true
			}).on('mousedown', function () {
				this.attr('zlevel',++temp);
				
			}).on('mouseup', function () {
				//this.attr('zlevel',++temp);
				//this.clearLayer();
					//sketchpad.redraw(sketchpad.strokes);
					//sketchpad.redrawtext(sketchpad.textarr);
			}).on('mousewheel',function(ev){
				var e = (ev||event).wheelDelta/20;
				//设置缩放大小
				this.attr('scale',[this.scale[0]+= e,this.scale[1]+= e]);
				//设置缩放中心
				this.attr('origin',[this.style.x+this.style.width/2,this.style.y+this.style.height/2]);
			}).on('dblclick',function(ev){
				//设置旋转角度
				this.attr('rotation',[this.rotation-Math.PI/12]);
				//设置旋转中心
				this.attr('origin',[this.style.x+this.style.width/2,this.style.y+this.style.height/2]);
			});
			group.add(img1);
			idCount++;
			zr.add(group);
			//oCan.drawImage(img,stroke.x-w/2,stroke.y,w,h);
			document.body.style.cursor = "default";
		}
	}
};
</script>
<body>
		<div class="container" id="container">
			  <canvas width="1024" height="768" class="sketchpad" id="sketchpad"><canvas>
		</div>
</body></html>

**Comment by qiaoaimi** [comment]
请您帮着看下，有什么解决办法吗？

**Comment by qiaoaimi** [comment]
原绘画内容，我们这边做了保存，可以在指定位置执行重绘，但我在mouseup事件里执行重画程序后，仅会保留zrender插图部分内容，其它内容还是会被清空。拖拽等操作后zrende在up事件后还会在哪里对画布做了清理工作？是在哪里重新绘制？我追了下源码，没太追明白？还请指导下？

**Comment by pissang** [comment]
不要在 zrender 的画布上执行自定义的 canvas 绘图，zrender 每一帧会清空画布重绘

**Comment by qiaoaimi** [comment]
没有可调整办法吗？我只需要插入图片、图片可放大、缩小、移动、旋转这几个功能就可以。或者您能不能指导下，这几个主要功能在哪？我改个简单版的？

**Comment by pissang** [comment]
都用 zrender 提供的接口添加删除更新图形

**Comment by qiaoaimi** [comment]
zrender 添加，删除，更新图形的接口是哪个？

**Comment by qiaoaimi** [comment]
谢谢了，我自己再想办法吧。
