### ISSUE TITLE
Set DOMMatrix in wrong order

### ISSUE THREAD

**Issue by Frezc** [ecomfe/zrender#850]
translate在矩阵里是要最后设置的，DOMMatrix提供的scale、translate方法相当于矩阵的 multiply，而非左乘（pre-multiply），所以在设置时需要按 translate->rotate->scale来设置，否则结果不正确。

目前在zrender里的结果时不对的

code at https://github.com/ecomfe/zrender/blob/master/src/canvas/graphic.ts#L80-L82

**Comment by pissang** [comment]
谢谢反馈，如果方便的话可以给我们提一个 Pull Request 修复该问题

**Comment by pengpeng9413** [comment]
我在用echart 最新版的仪表盘组件的时候，出现了以下错误
```js
Cannot read properties of null (reading 'setTransform')
```
code error at https://github.com/ecomfe/zrender/blob/master/src/canvas/graphic.ts#L74-L78
debugger 发现 canvasPattern 有时候是null, 此时的ctx 和 image 皆为true
更改成如下，方可成功编译
```ts
if (isImageReady(image)) {
        const canvasPattern = ctx.createPattern(image, pattern.repeat || 'repeat');
        if (
            typeof DOMMatrix === 'function'
            && canvasPattern && canvasPattern.setTransform   // setTransform may not be supported in some old devices.
        ) {
            const matrix = new DOMMatrix();
            matrix.rotateSelf(0, 0, (pattern.rotation || 0) / Math.PI * 180);
            matrix.scaleSelf((pattern.scaleX || 1), (pattern.scaleY || 1));
            matrix.translateSelf((pattern.x || 0), (pattern.y || 0));
            canvasPattern.setTransform(matrix);
        }
        return canvasPattern;
    }
```
以下是我的react simple demo
```tsx
import * as React from 'react';
import styled from 'styled-components';
import * as Echarts from 'echarts';

interface Props {
  data: any;
}

const getOptions = () => {
  const ImgInstance = new Image();
  ImgInstance.src = '/static/new/bg.png';
  return {
    tooltip: {
      formatter: '{a} <br/>{b} : {c}%',
    },
    axisLine: {
      lineStyle: {
        width: 85,
        opacity: 0,
      },
    },
    series: [
      {
        type: 'gauge',
        radius: '90%',
        axisLine: {
          show: true,
          lineStyle: {
            width: 1,
            opacity: 0,
          },
        },
        title: { show: true },
        detail: { show: true },
        splitLine: { show: true },
        axisTick: {
          length: 5,
          splitNumber: 7,
          lineStyle: {
            color: {
              image: ImgInstance,
              repeat: 'no-repeat',
            },
            width: 3,
          },
        },
        axisLabel: { show: true },
        pointer: {
          show: true,
          width: 3,
          icon:
            'image://data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNCIgaGVpZ2h0PSI2OCIgdmlld0JveD0iMCAwIDQgNjgiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICA8ZGVmcz4KICAgICAgICA8ZmlsdGVyIHg9Ii0yMTYuNyUiIHk9Ii05LjclIiB3aWR0aD0iNTMzLjMlIiBoZWlnaHQ9IjExOS40JSIgZmlsdGVyVW5pdHM9Im9iamVjdEJvdW5kaW5nQm94IiBpZD0iYSI+CiAgICAgICAgICAgIDxmZU9mZnNldCBkeD0iLTIiIGR5PSIyIiBpbj0iU291cmNlQWxwaGEiIHJlc3VsdD0ic2hhZG93T2Zmc2V0T3V0ZXIxIi8+CiAgICAgICAgICAgIDxmZUdhdXNzaWFuQmx1ciBzdGREZXZpYXRpb249Ii41IiBpbj0ic2hhZG93T2Zmc2V0T3V0ZXIxIiByZXN1bHQ9InNoYWRvd0JsdXJPdXRlcjEiLz4KICAgICAgICAgICAgPGZlQ29sb3JNYXRyaXggdmFsdWVzPSIwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwLjA5IDAiIGluPSJzaGFkb3dCbHVyT3V0ZXIxIiByZXN1bHQ9InNoYWRvd01hdHJpeE91dGVyMSIvPgogICAgICAgICAgICA8ZmVNZXJnZT4KICAgICAgICAgICAgICAgIDxmZU1lcmdlTm9kZSBpbj0ic2hhZG93TWF0cml4T3V0ZXIxIi8+CiAgICAgICAgICAgICAgICA8ZmVNZXJnZU5vZGUgaW49IlNvdXJjZUdyYXBoaWMiLz4KICAgICAgICAgICAgPC9mZU1lcmdlPgogICAgICAgIDwvZmlsdGVyPgogICAgPC9kZWZzPgogICAgPGcgZmlsdGVyPSJ1cmwoI2EpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSguNSAuNTU2KSIgZmlsbD0iI0VCMjE0OSIgZmlsbC1ydWxlPSJub256ZXJvIj4KICAgICAgICA8cGF0aCBkPSJNMi4yNS43NXYzMy40OTFhLjc1Ljc1IDAgMCAxIC43NS43NXYzMi4wNjVIMFYzNC45OWEuNzUuNzUgMCAwIDEgLjc1LS43NVYuNzVhLjc1Ljc1IDAgMCAxIDEuNSAweiIvPgogICAgPC9nPgo8L3N2Zz4K',
        },
        itemStyle: {},
        data: [
          {
            value: 20,
            name: 'test gauge',
          },
        ],
      },
    ],
  };
};

export default React.memo((props: Props) => {
  const [options, setOptions] = React.useState<any>(getOptions);
  const echartsRef = React.useRef<HTMLDivElement>(null);
  const imgRef = React.useRef<HTMLImageElement>(null)

  React.useEffect(() => {
    if (echartsRef.current) {
      // 将echart 挂载到组件实例上
      const instanceOfEcharts = Echarts.init(echartsRef.current);
      instanceOfEcharts.setOption(options);
    }
  }, [echartsRef]);

  React.useEffect(() => {}, [props.data]);

  return (
    <div style={{ width: '100%', height: '100%' }}>
      <div
        className='gauge-chart'
        style={{ width: '100%', height: '200px' }}
        ref={echartsRef}
      ></div>
    </div>
  );
});
```

**Comment by Frezc** [comment]
> 我在用echart 最新版的仪表盘组件的时候，出现了以下错误
> 
> ```js
> Cannot read properties of null (reading 'setTransform')
> ```
> 
> code error at https://github.com/ecomfe/zrender/blob/master/src/canvas/graphic.ts#L74-L78 debugger 发现 canvasPattern 有时候是null, 此时的ctx 和 image 皆为true 更改成如下，方可成功编译
> 
> ```ts
> if (isImageReady(image)) {
>         const canvasPattern = ctx.createPattern(image, pattern.repeat || 'repeat');
>         if (
>             typeof DOMMatrix === 'function'
>             && canvasPattern && canvasPattern.setTransform   // setTransform may not be supported in some old devices.
>         ) {
>             const matrix = new DOMMatrix();
>             matrix.rotateSelf(0, 0, (pattern.rotation || 0) / Math.PI * 180);
>             matrix.scaleSelf((pattern.scaleX || 1), (pattern.scaleY || 1));
>             matrix.translateSelf((pattern.x || 0), (pattern.y || 0));
>             canvasPattern.setTransform(matrix);
>         }
>         return canvasPattern;
>     }
> ```
> 
> 以下是我的react simple demo
> 
> ```tsx
> import * as React from 'react';
> import styled from 'styled-components';
> import * as Echarts from 'echarts';
> 
> interface Props {
>   data: any;
> }
> 
> const getOptions = () => {
>   const ImgInstance = new Image();
>   ImgInstance.src = '/static/new/bg.png';
>   return {
>     tooltip: {
>       formatter: '{a} <br/>{b} : {c}%',
>     },
>     axisLine: {
>       lineStyle: {
>         width: 85,
>         opacity: 0,
>       },
>     },
>     series: [
>       {
>         type: 'gauge',
>         radius: '90%',
>         axisLine: {
>           show: true,
>           lineStyle: {
>             width: 1,
>             opacity: 0,
>           },
>         },
>         title: { show: true },
>         detail: { show: true },
>         splitLine: { show: true },
>         axisTick: {
>           length: 5,
>           splitNumber: 7,
>           lineStyle: {
>             color: {
>               image: ImgInstance,
>               repeat: 'no-repeat',
>             },
>             width: 3,
>           },
>         },
>         axisLabel: { show: true },
>         pointer: {
>           show: true,
>           width: 3,
>           icon:
>             'image://data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNCIgaGVpZ2h0PSI2OCIgdmlld0JveD0iMCAwIDQgNjgiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICA8ZGVmcz4KICAgICAgICA8ZmlsdGVyIHg9Ii0yMTYuNyUiIHk9Ii05LjclIiB3aWR0aD0iNTMzLjMlIiBoZWlnaHQ9IjExOS40JSIgZmlsdGVyVW5pdHM9Im9iamVjdEJvdW5kaW5nQm94IiBpZD0iYSI+CiAgICAgICAgICAgIDxmZU9mZnNldCBkeD0iLTIiIGR5PSIyIiBpbj0iU291cmNlQWxwaGEiIHJlc3VsdD0ic2hhZG93T2Zmc2V0T3V0ZXIxIi8+CiAgICAgICAgICAgIDxmZUdhdXNzaWFuQmx1ciBzdGREZXZpYXRpb249Ii41IiBpbj0ic2hhZG93T2Zmc2V0T3V0ZXIxIiByZXN1bHQ9InNoYWRvd0JsdXJPdXRlcjEiLz4KICAgICAgICAgICAgPGZlQ29sb3JNYXRyaXggdmFsdWVzPSIwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwLjA5IDAiIGluPSJzaGFkb3dCbHVyT3V0ZXIxIiByZXN1bHQ9InNoYWRvd01hdHJpeE91dGVyMSIvPgogICAgICAgICAgICA8ZmVNZXJnZT4KICAgICAgICAgICAgICAgIDxmZU1lcmdlTm9kZSBpbj0ic2hhZG93TWF0cml4T3V0ZXIxIi8+CiAgICAgICAgICAgICAgICA8ZmVNZXJnZU5vZGUgaW49IlNvdXJjZUdyYXBoaWMiLz4KICAgICAgICAgICAgPC9mZU1lcmdlPgogICAgICAgIDwvZmlsdGVyPgogICAgPC9kZWZzPgogICAgPGcgZmlsdGVyPSJ1cmwoI2EpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSguNSAuNTU2KSIgZmlsbD0iI0VCMjE0OSIgZmlsbC1ydWxlPSJub256ZXJvIj4KICAgICAgICA8cGF0aCBkPSJNMi4yNS43NXYzMy40OTFhLjc1Ljc1IDAgMCAxIC43NS43NXYzMi4wNjVIMFYzNC45OWEuNzUuNzUgMCAwIDEgLjc1LS43NVYuNzVhLjc1Ljc1IDAgMCAxIDEuNSAweiIvPgogICAgPC9nPgo8L3N2Zz4K',
>         },
>         itemStyle: {},
>         data: [
>           {
>             value: 20,
>             name: 'test gauge',
>           },
>         ],
>       },
>     ],
>   };
> };
> 
> export default React.memo((props: Props) => {
>   const [options, setOptions] = React.useState<any>(getOptions);
>   const echartsRef = React.useRef<HTMLDivElement>(null);
>   const imgRef = React.useRef<HTMLImageElement>(null)
> 
>   React.useEffect(() => {
>     if (echartsRef.current) {
>       // 将echart 挂载到组件实例上
>       const instanceOfEcharts = Echarts.init(echartsRef.current);
>       instanceOfEcharts.setOption(options);
>     }
>   }, [echartsRef]);
> 
>   React.useEffect(() => {}, [props.data]);
> 
>   return (
>     <div style={{ width: '100%', height: '100%' }}>
>       <div
>         className='gauge-chart'
>         style={{ width: '100%', height: '200px' }}
>         ref={echartsRef}
>       ></div>
>     </div>
>   );
> });
> ```

这个报错我也会出现，是因为图片还未加载完就进入了`createCanvasPattern `方法导致创建pattern失败，调用栈如下，我提个mr一起修了吧
```
createCanvasPattern (graphic.js:52)
brushPath (graphic.js:110)
brush (graphic.js:505)
CanvasPainter._doPaintEl (Painter.js:327)
repaint (Painter.js:262)
_loop_1 (Painter.js:293)
CanvasPainter._doPaintList (Painter.js:303)
CanvasPainter._paintList (Painter.js:180)
CanvasPainter.refresh (Painter.js:121)
ZRender.refreshImmediately (zrender.js:127)
ZRender._flush (zrender.js:142)
update (zrender.js:78)
Animation.update (Animation.js:88)
step (Animation.js:97)
requestAnimationFrame (async)
step (Animation.js:96)
requestAnimationFrame (async)
step (Animation.js:96)
requestAnimationFrame (async)
step (Animation.js:96)
requestAnimationFrame (async)
step (Animation.js:96)
requestAnimationFrame (async)
step (Animation.js:96)
requestAnimationFrame (async)
step (Animation.js:96)
requestAnimationFrame (async)
step (Animation.js:96)
requestAnimationFrame (async)
step (Animation.js:96)
requestAnimationFrame (async)
Animation._startLoop (Animation.js:100)
Animation.start (Animation.js:108)
ZRender (zrender.js:81)
init (zrender.js:244)
ECharts (echarts.js:255)
init (echarts.js:2190)
parcelRequire.index.ts.echarts/core (index.ts:26)
newRequire (src.77de5100.js:47)
(anonymous) (src.77de5100.js:81)
(anonymous) (src.77de5100.js:120)
```
