### ISSUE TITLE
文档描述BoundingRect.intersect和实际不一致

### ISSUE THREAD

**Issue by hackeryutu** [ecomfe/zrender#887]
![image](https://user-images.githubusercontent.com/16240260/150730544-042b3fc9-87f9-4f26-afdf-51f8b8b5d3ce.png)

实际返回的是一个boolean值

**Comment by chengzhanpeng** [comment]
你使用的是哪个版本的js文件呢，他这个文档好像不是最新的。

**Comment by Ovilia** [comment]
https://github.com/ecomfe/zrender-doc 欢迎提 pr

**Comment by Jeggery** [comment]
他这文档都是八百年的老版本
