### ISSUE TITLE
多段曲线是否已经不支持 Catmull-Rom spline 插值算法了？

### ISSUE THREAD

**Issue by FourLeafTec** [ecomfe/zrender#900]
实测无论是Polyline还是Polygon，smooth属性设置为spline都就不进行绘制了

并且在仓库中搜索smoothSpline方法也并未被任何代码使用

现在是不是不支持Catmull-Rom spline 插值算法了？

**Comment by pissang** [comment]
https://github.com/ecomfe/zrender/blob/master/src/graphic/helper/smoothSpline.ts

**Comment by FourLeafTec** [comment]
了解了，跟我想的一样
