### ISSUE TITLE
新版本vue项目中import不了

### ISSUE THREAD

**Issue by yicheng2022** [ecomfe/zrender#907]
![image](https://user-images.githubusercontent.com/103647012/163503870-0cbfceb9-c279-420a-8d81-360aa5cea09f.png)

![image](https://user-images.githubusercontent.com/103647012/163503832-1353344e-2aa3-4013-a1e7-c6ce866f4bf0.png)

**Comment by yicheng2022** [comment]
改为 import * as zrender from 'zrender'

**Comment by bbhxwl** [comment]
> 改为 import * as zrender from 'zrender'

vue2 能这样用么。我出这个错误。
 Error in mounted hook: "Error: Renderer 'undefined' is not imported. Please import it first."

**Comment by bbhxwl** [comment]
> 改为 import * as zrender from 'zrender'

好像nuxt的话，不能服务端渲染，出错。
