### ISSUE TITLE
使用一个变量作为参数指定多个元素的位置后，若拖动一个元素，其他元素的位置属性值也会被同步修改

### ISSUE THREAD

**Issue by evaydh** [ecomfe/zrender#914]
我不确定这是否是一个Bug还是一个特性，如果在新建多个元素的过程中，使用同一个变量指定这些元素的`position`属性，同时`draggable`属性为`true`的情况下，拖动某一个元素，会同步修改其他元素的`position`属性
```javascript
const pos = [0, 10]

const redRect = new zrender.Rect({
  position: pos,
  shape: { width: 100, height: 50 },
  style: { fill: 'red' },
  draggable: true
})

const greenRect= new zrender.Rect({
  position: pos,
  shape: { width: 100, height: 50 },
  style: { fill: 'green' },
  draggable: true
})

const zr = zrender.init('dom')

zr.add(redRect)
zr.add(greenRect)
```

通过变量`pos`指定`redRect` 和 `greenRect`的`position`属性后，若只拖动`redRect`，`greenRect`的`position`属性也会被同步修改，但实际显示的位置并不会发生变化。

这种修改是双向的，只拖动`greenRect`，`redRect`的`position`属性也会修改。

同样的情况在group上也会出现。我确定过`redRect`，`greenRect`的`id`属性是不一样的。

**Comment by plainheart** [comment]
同一个数组的引用地址是一样的，在赋值给其他元素时应该先利用 `pos.slice()` 克隆一份新数组。

**Comment by evaydh** [comment]
> 同一个数组的引用地址是一样的，在赋值给其他元素时应该先利用 `pos.slice()` 克隆一份新数组。

感谢，是我犯傻了
