### ISSUE TITLE
新版的Image设置text无效

### ISSUE THREAD

**Issue by fssh** [ecomfe/zrender#924]
依据官方api，Image是继承自Displayable这个抽象类的。
对于v5.3.2，给Image的Style设置 text、textFill、textOffset、fontSize后，文字无法显示；而对于v4.3.2，却可以显示。
希望新版能修复这个bug。

**Comment by plainheart** [comment]
请改用 `setTextConfig` 和 `setTextContent`。见 [v5 升级指南](https://echarts.apache.org/handbook/zh/basics/release-note/v5-upgrade-guide/#:~:text=%E5%9B%BE%E5%BD%A2%E5%85%83%E7%B4%A0%E6%97%B6%E3%80%82-,Text%20%E7%9B%B8%E5%85%B3%E7%9A%84%E5%B1%9E%E6%80%A7%E8%A2%AB%E6%94%B9%E5%8F%98,-%EF%BC%9A)
