### ISSUE TITLE
有计划结合react-native-skia库来支持rn吗?

### ISSUE THREAD

**Issue by SilentMelody** [ecomfe/zrender#931]
你好, shopify  开发的 React Native Skia 库实现了 rn 对 canvas 的支持, 如果 zrender 能基于此实现一套rn的渲染器, 那 echarts 就可以直接在 rn 中使用, 而不需要通过 webview 的方式.
不知道我们在这个方面有没有计划~谢谢

**Comment by Ovilia** [comment]
没有，感兴趣的话可以自己实现，方式类似微信小程序 ECharts https://github.com/ecomfe/echarts-for-weixin/blob/master/ec-canvas/ec-canvas.js

**Comment by SilentMelody** [comment]
了解~谢谢
