### ISSUE TITLE
能否把./graphic/helper/parseText.ts中的类和方法加入到exports.ts中公开出来

### ISSUE THREAD

**Issue by burnup123** [ecomfe/zrender#934]
我想用zrender做个简单的富文本编辑器，想利用./graphic/helper/parseText.ts中的类和方法，但是无法import。
能否把它们加入到exports.ts中公开出来？

**Comment by junguoguo** [comment]
> burnup123 , 您好，烦请看到这条留言后，联系下我（找不到您联系方式），有个代码问题需要和你沟通下，谢谢
我的联系方式微信： ajun-guo

**Comment by junguoguo** [comment]
> 我想用zrender做个简单的富文本编辑器，想利用./graphic/helper/parseText.ts中的类和方法，但是无法import。 能否把它们加入到exports.ts中公开出来？

burnup123，您好，烦请看到这条留言后，联系下我（找不到您联系方式），有个代码问题需要和你沟通下，谢谢
我的联系方式微信： ajun-guo
