### ISSUE TITLE
肯请大佬更新一下5.0文档。

### ISSUE THREAD

**Issue by ChangeMoreNate** [ecomfe/zrender#943]
查看了一下之前的提问，去年都有更新了  zrender的文档还是没变化。泪目！！！ 肯请大佬们有时间更新一下文档。拜托了！！

**Comment by Ovilia** [comment]
大部分接口都没有变，如果有发现文档没有即使更新的地方，请具体指出哪里有问题，或者自己提个 PR，谢谢！

**Comment by ChangeMoreNate** [comment]
> 大部分接口都没有变，如果有发现文档没有即使更新的地方，请具体指出哪里有问题，或者自己提个 PR，谢谢！

好吧~ 正在使用zrender做项目 遇到了问题会提 届时麻烦解答 感谢
