### ISSUE TITLE
 怎么让图片充满整个canvas

### ISSUE THREAD

**Issue by bbhxwl** [ecomfe/zrender#944]
比如我canvas 基于页面是百分百，图片是个8000像素的，我应该怎么让他能正好缩放显示在我这个canvas 上

**Comment by Ovilia** [comment]
可以通过 [zr.getWidth](https://ecomfe.github.io/zrender-doc/public/api.html#getwidth)、[zr.getHeight](https://ecomfe.github.io/zrender-doc/public/api.html#getheight) 获得画布的宽度和高度。

**Comment by bbhxwl** [comment]
> 可以通过 [zr.getWidth](https://ecomfe.github.io/zrender-doc/public/api.html#getwidth)、[zr.getHeight](https://ecomfe.github.io/zrender-doc/public/api.html#getheight) 获得画布的宽度和高度。

想渲染游戏地图，好像这个不适合，改用其他库方案了。地图有80M的图片。

**Comment by Ovilia** [comment]
好的，的确不太建议使用 ZRender，ZRender 主要还是服务于 Apache ECharts 的特殊场景，可能不太适合游戏场景。考虑到体积问题，对于 ECharts 用不到的功能一般也不会在 ZRender 中支持。
