### ISSUE TITLE
5.3.2 elm 设置 zLevel 不生效，后添加的元素即使zLevel小 但是还是会显示在zLevel大的元素前

### ISSUE THREAD

**Issue by ChangeMoreNate** [ecomfe/zrender#946]

**Comment by Ovilia** [comment]
代码？

**Comment by ChangeMoreNate** [comment]
`<template>
  <div class="render" ref="render"></div>
</template>

<script>
import * as zrender from "zrender";

export default {
  name: 'HelloWorld',
  data() {
    return {
      zr: null,
      windowWidth: 0,
      windowHeight: 0
    }
  },
  created() {
    this.windowWidth = document.body.clientWidth
    this.windowHeight = document.body.clientHeight
  },
  mounted() {
    this.init()
  },
  methods: {
    init() {
      this.zr = zrender.init(this.$refs.render, {
        renderer: "svg",
        width: this.windowWidth,
        height: this.windowHeight
      });
      const g = this.g = new zrender.Group()
      const c1 = new zrender.Circle({
        name: 'c1',
        shape: {
          cx: 300,
          cy: 300,
          r: 200
        },
        style: {
          fill: 'red'
        },
        zlevel: 999
      })

      const c2 = new zrender.Circle({
        name: 'c2',
        shape: {
          cx: 400,
          cy: 400,
          r: 200
        },
        style: {
          fill: 'green'
        },
        zlevel: 10
      })

      const img1 = new zrender.Image({
        name: 'img1',
        style: {
          image: require('../assets/logo.png'),
          width: 300,
          height: 900,
          x: 600,
          y: 300,
          zlevel: 10
        }
      })

      const img2 = new zrender.Image({
        name: 'img2',
        style: {
          image: require('../assets/logo.png'),
          width: 300,
          height: 300,
          x: 630,
          y: 500,
          zlevel: 999
        },
      })

      g.add(img1)
      g.add(img2)
      g.add(c1)
      g.add(c2)
      this.zr.add(g)
    }
  }
}
</script>
<style scoped>
.render {
  width: 100vw;
  height: 100vh;
}
</style>
`

测试下来 image 的zlevel不生效  图形的zlevel 是生效的

**Comment by ChangeMoreNate** [comment]
抱歉 仔细检查以后发现zlevel设置在style 之中了，再次测试 在group中设置zlevel 无效，转而在元素中设置zlevel 已经生效解决了目前的我们遇到的问题。
