### ISSUE TITLE
measureText 计算 fontSize 有误

### ISSUE THREAD

**Issue by zhiqingchen** [ecomfe/zrender#947]
https://github.com/ecomfe/zrender/blob/e5d275f5d08b3093e3e218843c593f000f86d62f/src/core/platform.ts#L75-L79

DEFAULT_FONT 为 `12px sans-serif`

运行时为 `normal normal 12px sans-serif`

```js
font = font || DEFAULT_FONT;
const res = /^([0-9]*?)px$/.exec(font);
const fontSize = +(res && res[1]) || DEFAULT_FONT_SIZE;
```

res 为 null, fontSize 只能为 DEFAULT_FONT_SIZE

**Comment by Ovilia** [comment]
`normal normal 12px sans-serif` 是怎么来的？请提供一个调用时的代码
