### ISSUE TITLE
我怎么缩放能不改变原来的布局

### ISSUE THREAD

**Issue by bbhxwl** [ecomfe/zrender#948]
比如我有个图片，4000x4000像素，全屏显示，我让一个文字在x:100,y:100的坐标显示，我这个图片放大，只能显示局部，显示不了全部4000x4000，然后我的这个文字，还能在原来比例的100，100 像素点

**Comment by Clloz** [comment]
将两个元素放到一个group里面，然后缩放应用到 group 上
