### ISSUE TITLE
这种图形应该怎么画

### ISSUE THREAD

**Issue by bbhxwl** [ecomfe/zrender#955]
有游戏人物是个原点，有个尖能看出朝向，还有个绿线，这是用三个图形画么，还是多边形，一下就能画出来？
三个图形画的话能明白，用圆形，三角形，和一个线 组成
![image](https://user-images.githubusercontent.com/26525599/194245701-2f2c0b0c-8950-47f5-b184-ded7c9f43ac1.png)

**Comment by Ovilia** [comment]
建议用贴图，或者也可以用 Path。其实复杂的游戏场景并不推荐使用 zrender，它只是用来为 echarts 的图表场景做底层渲染的，很多游戏里需要用到的功能可能并不支持，建议优先考虑专门为游戏做的渲染引擎。

**Comment by bbhxwl** [comment]
> 建议用贴图，或者也可以用 Path。其实复杂的游戏场景并不推荐使用 zrender，它只是用来为 echarts 的图表场景做底层渲染的，很多游戏里需要用到的功能可能并不支持，建议优先考虑专门为游戏做的渲染引擎。

只是渲染游戏的地图，不算是游戏，应该不太复杂。
