### ISSUE TITLE
nuxt 用dev模式正常，build后，运行页面出错。

### ISSUE THREAD

**Issue by bbhxwl** [ecomfe/zrender#960]
Pt[l] is not a constructor
![image](https://user-images.githubusercontent.com/26525599/194789267-475b6bfd-7be2-4566-8396-4eb356ca8c49.png)

**Comment by bbhxwl** [comment]
5的版本有问题，4.3.2 没事。

**Comment by liu3104009029** [comment]
5版本至今没修复

**Comment by bbhxwl** [comment]
> 5版本至今没修复

可能放弃了吧。
