### ISSUE TITLE
defaultWidthMapStr 基础字体计算问题

### ISSUE THREAD

**Issue by shinken008** [ecomfe/zrender#972]
https://github.com/ecomfe/zrender/blob/b952ca1c3313901dcab81d30c674060624ce3cb1/src/core/platform.ts#L35

请问下 defaultWidthMapStr这个 mapstring 是怎么生成的呢，如果是其他基础字体设置的话，比如中文的话，用 sans-serif 宽度就会不够（不用这个字体的原因是sans-serif 没有中文，使用 skia 绘制不会向下兼容匹配其他字体乱码，尴尬）。所以我想使用一个中文字体，生成一份对应的 map 文件呢，可能对应的 getTextWidthMap也需要调整。

**Comment by plainheart** [comment]
https://github.com/ecomfe/zrender/blob/master/test/asciiWidthMap.html

**Comment by shinken008** [comment]
> https://github.com/ecomfe/zrender/blob/master/test/asciiWidthMap.html

赞
