### ISSUE TITLE
在vue项目中，发布后页面抛constructor异常

### ISSUE THREAD

**Issue by liu3104009029** [ecomfe/zrender#981]
在vue-element项目中，引入zrender5.4.1版本，通过 npm run build:prod 发布，通过npm run serve运行
在第一次通过vue框架的左侧菜单栏打开页面时，zrender画的页面正常显示，然后点击浏览器的刷新按钮，页面就没有显示，查看浏览器控制台，提示 ：TypeError: Ir[o] is not a constructor
 代码：
<template>
    <div class="app-container" style="height:100%">
        <el-main>
            <div id="mapContainer" class="container" :style="{ 'width': '100px', 'height': '500px' }"></div>
        </el-main>

    </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted  } from "vue";
import * as zrender from 'zrender'  

onMounted(() => { 

    document.onkeyup = e => {
        e.preventDefault()
    }

    const mpC = document.getElementById('mapContainer')
    var zr = zrender.init(mpC, { width: 1000, height: 500 })
    var curve = new zrender.BezierCurve({
        shape: {
            x1: 10,
            y1: 400,
            cpx1: 0,
            cpy1: 0,
            cpx2: 0,
            cpy2: 0,
            x2: 300,
            y2: 30
        },
        draggable: true
    });

    zr.add(curve);
}) 

</script>

![image](https://user-images.githubusercontent.com/35867372/205573391-8697a4f6-b00a-4eec-a328-643ddf418c4d.png)

![image](https://user-images.githubusercontent.com/35867372/205573095-308854d7-a282-432a-bf56-8733c0d07820.png)

**Comment by liu3104009029** [comment]
很奇怪，在页面加一个echarts部件就不会发生这个问题，不知道啥原因！！！！

**Comment by plainheart** [comment]
应该是因为渲染器注册的代码被 tree-shaked 了，试试手动加上。
```js
import * as zrender from 'zrender' ;
import CanvasPainter from 'zrender/lib/canvas/Painter';
zrender.registerPainter('canvas', CanvasPainter);
```

**Comment by liu3104009029** [comment]
解决了，非常感谢！！！
