### ISSUE TITLE
官网API文档太旧，请求更新到最新版本的API文档

### ISSUE THREAD

**Issue by chxb** [ecomfe/zrender#986]
如题。官网API文档()太旧，还是基于4.3.2版本的，查到很多API都失效或者参数不对，用起来十分不便。请求zrender开发者能更新官网文档到最新API版本。官网API地址：https://ecomfe.github.io/zrender-doc/public/api.html

**Comment by Ovilia** [comment]
建议碰到对不上的问题就提 PR 解决
